# Generated by Django 5.1.2 on 2026-04-09 00:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram: your handle starting with @')),
                ('bio', models.TextField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='artist_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='show_images')),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curators', models.ManyToManyField(to='gallery.artist')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='show_images')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gallery.show')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('end_year', models.IntegerField()),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='Start_year: only fill in if different than end_year')),
                ('medium', models.TextField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dimensions: LxWxD in inches')),
                ('image', models.ImageField(null=True, upload_to='artwork_images')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price: numeric price')),
                ('pricing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pricing: anything more sophisticated like "Upon request" or "NFS"')),
                ('replacement_cost', models.FloatField(blank=True, null=True, verbose_name='Replacment Cost: redo cost in the rare case that it gets stolen or damaged')),
                ('is_sold', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('installation', models.TextField(blank=True, null=True, verbose_name='Installation: optional instructions for installing your work')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(related_name='artworks', to='gallery.artist')),
                ('shows', models.ManyToManyField(related_name='artworks', to='gallery.show')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
