# Generated by Django 5.1.2 on 2026-04-09 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_role_and_visibility_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Artist = apps.get_model('gallery', 'Artist')
    Artwork = apps.get_model('gallery', 'Artwork')
    Event = apps.get_model('gallery', 'Event')
    Show = apps.get_model('gallery', 'Show')
    Tag = apps.get_model('gallery', 'Tag')

    groups = {}
    for name in ('artist', 'curator', 'staff'):
        groups[name], _ = Group.objects.get_or_create(name=name)

    open_call_tag, _ = Tag.objects.get_or_create(slug='open-call', defaults={'name': 'Open Call'})

    artist_user_ids = Artist.objects.exclude(user_id__isnull=True).values_list('user_id', flat=True).distinct()
    groups['artist'].user_set.add(*artist_user_ids)

    for show in Show.objects.prefetch_related('curators__user').all():
        curator_artist = next((artist for artist in show.curators.all() if artist.user_id), None)
        if curator_artist:
            show.managing_curator_id = curator_artist.user_id
            show.save(update_fields=['managing_curator'])
            groups['curator'].user_set.add(curator_artist.user_id)
        show.artists.set(Artist.objects.filter(artworks__shows=show).distinct())
        if getattr(show, 'is_open_call', False):
            show.tags.add(open_call_tag)

    for event in Event.objects.select_related('show').all():
        if event.show_id and event.show.managing_curator_id:
            event.managing_curator_id = event.show.managing_curator_id
            event.save(update_fields=['managing_curator'])

    for artwork in Artwork.objects.prefetch_related('artists__user').all():
        artwork.is_public = True
        owner_artist = next((artist for artist in artwork.artists.all() if artist.user_id), None)
        if owner_artist:
            artwork.created_by_id = owner_artist.user_id
        artwork.save(update_fields=['is_public', 'created_by'])
        if getattr(artwork, 'open_call_available', False):
            artwork.tags.add(open_call_tag)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='open_call_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='managing_curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='managing_curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='is_open_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork_images'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='shows',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='gallery.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='curators',
            field=models.ManyToManyField(blank=True, to='gallery.artist'),
        ),
        migrations.AddField(
            model_name='show',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='shows', to='gallery.artist'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('curators', models.ManyToManyField(blank=True, related_name='curator_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artists', to='gallery.tag'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='gallery.tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='gallery.tag'),
        ),
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='shows', to='gallery.tag'),
        ),
        migrations.RunPython(seed_role_and_visibility_data, noop_reverse),
    ]
