# Generated by Django 5.1.2 on 2026-04-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_normalize_public_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
