# Generated by Django 5.1.2 on 2026-05-26 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_artist_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='open_call_available',
        ),
        migrations.AddField(
            model_name='show',
            name='decision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ArtworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('statement', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='gallery.artwork')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='gallery.show')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('show', 'artwork')},
            },
        ),
    ]
