# Generated by Django 5.1.2 on 2026-05-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_artwork_open_call_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='managing_curator',
        ),
        migrations.RemoveField(
            model_name='show',
            name='managing_curator',
        ),
    ]
