# Generated by Django 5.1.2 on 2026-05-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_event_managing_curator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='venmo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Venmo: your username starting with @'),
        ),
    ]
