# Generated by Django 5.1.2 on 2026-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_artist_venmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='depth_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Depth (inches, optional)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Height (inches)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Width (inches)'),
        ),
    ]
