# Generated by Django 5.1.2 on 2026-05-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_populate_dimension_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(help_text='Title of artwork', max_length=255),
        ),
    ]
