# Generated by Django 5.1.2 on 2026-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_artwork_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location (address or site description)'),
        ),
        migrations.AddField(
            model_name='show',
            name='show_type',
            field=models.CharField(choices=[('gallery', 'Gallery Show'), ('public_art', 'Public Art Site')], default='gallery', max_length=32),
        ),
    ]
