# Generated by Django 5.1.2 on 2026-05-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_show_location_show_show_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_public',
        ),
    ]
