# Generated by Django 5.1.2 on 2026-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='review_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Review deadline (for jurors)'),
        ),
        migrations.AlterField(
            model_name='show',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='curated_shows', to='gallery.artist'),
        ),
    ]
