# Generated by Django 5.1.2 on 2026-05-29 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_show_review_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowArtworkNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_numbers', to='gallery.artwork')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_numbers', to='gallery.show')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('show', 'artwork'), ('show', 'number')},
            },
        ),
    ]
