# Generated by Django 5.1.2 on 2026-05-29 13:45

from django.db import migrations, models


def copy_status_to_decision(apps, schema_editor):
    ArtworkSubmission = apps.get_model('gallery', 'ArtworkSubmission')
    for sub in ArtworkSubmission.objects.filter(status__in=['selected', 'rejected']):
        sub.curator_decision = sub.status
        sub.status = 'submitted'
        sub.save(update_fields=['curator_decision', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_show_artwork_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworksubmission',
            name='curator_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='undecided', max_length=20),
        ),
        migrations.AlterField(
            model_name='artworksubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.RunPython(copy_status_to_decision, migrations.RunPython.noop),
    ]
