# Generated by Django 5.1.2 on 2026-06-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_add_curator_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('under_consideration', 'Under Consideration'), ('open_call', 'Open Call'), ('in_review', 'In Review'), ('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='under_consideration', max_length=32),
        ),
    ]
