# Generated by Django 5.1.2 on 2026-06-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_add_show_status_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='artists',
        ),
    ]
