# Generated by Django 5.1.2 on 2026-06-08 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_remove_show_artists_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='is_open_call',
        ),
        migrations.AddField(
            model_name='show',
            name='submission_type',
            field=models.CharField(choices=[('open', 'Open Call'), ('invited', 'Invitation Only')], default='open', max_length=16, verbose_name='Submission type'),
        ),
        migrations.CreateModel(
            name='ShowInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_invitations', to='gallery.artist')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gallery.show')),
            ],
            options={
                'ordering': ['sent_at'],
                'unique_together': {('show', 'email')},
            },
        ),
    ]
