# Generated by Django 5.1.2 on 2026-06-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_replace_is_open_call_with_submission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworksubmission',
            name='statement',
        ),
    ]
