# Generated by Django 5.1.2 on 2026-06-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0026_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
