# Generated by Django 5.1.2 on 2026-06-11 03:45

from django.db import migrations


def normalise_social_fields(apps, schema_editor):
    Artist = apps.get_model('gallery', 'Artist')
    for artist in Artist.objects.exclude(instagram='').exclude(instagram__isnull=True):
        if not artist.instagram.startswith('@'):
            artist.instagram = '@' + artist.instagram.strip()
            artist.save(update_fields=['instagram'])
    for artist in Artist.objects.exclude(venmo='').exclude(venmo__isnull=True):
        if not artist.venmo.startswith('@'):
            artist.venmo = '@' + artist.venmo.strip()
            artist.save(update_fields=['venmo'])
    for artist in Artist.objects.exclude(website='').exclude(website__isnull=True):
        if '://' not in artist.website:
            artist.website = 'https://' + artist.website.strip()
            artist.save(update_fields=['website'])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0027_alter_artist_phone'),
    ]

    operations = [
        migrations.RunPython(normalise_social_fields, migrations.RunPython.noop),
    ]
