# Generated by Django 5.1.2 on 2026-06-11 03:51

import re

from django.db import migrations


def reformat_us_phone(phone):
    """Return (area, exchange, number) formatted string for 10-digit US numbers.

    Strips leading country code 1 if present (11 digits starting with 1).
    Returns the original string unchanged for anything else.
    """
    digits = re.sub(r'\D', '', phone)
    if len(digits) == 11 and digits[0] == '1':
        digits = digits[1:]
    if len(digits) == 10:
        return f'({digits[:3]}) {digits[3:6]}-{digits[6:]}'
    return phone


def reformat_phones(apps, schema_editor):
    Artist = apps.get_model('gallery', 'Artist')
    for artist in Artist.objects.exclude(phone=''):
        reformatted = reformat_us_phone(artist.phone)
        if reformatted != artist.phone:
            artist.phone = reformatted
            artist.save(update_fields=['phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0028_normalise_artist_social_fields'),
    ]

    operations = [
        migrations.RunPython(reformat_phones, migrations.RunPython.noop),
    ]
