# Generated by Django 5.1.2 on 2026-06-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0029_reformat_artist_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTreeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Link tree entry',
                'verbose_name_plural': 'Link tree entries',
                'ordering': ['order', 'name'],
            },
        ),
    ]
