# Generated by Django 5.1.2 on 2026-06-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0030_linktreeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
