# Generated by Django 5.1.2 on 2026-06-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_add_artist_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artwork_images')),
                ('order', models.IntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplemental_images', to='gallery.artwork')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
