# Generated by Django 5.1.2 on 2026-07-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_add_artworkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='blind_review',
            field=models.BooleanField(default=False, help_text='Hide artist names from jurors and curators during review and selection.', verbose_name='Blind review'),
        ),
    ]
