# Generated by Django 5.1.2 on 2026-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0033_blind_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collected_by', to='gallery.artwork'),
        ),
    ]
