# Generated by Django 5.1.2 on 2026-07-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0035_collection_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedartwork',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='savedartwork',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
