# Generated by Django 5.1.2 on 2026-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0036_savedartwork_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpiece',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
