# Generated by Django 5.1.2 on 2026-07-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0037_collectionpiece_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL (video, website, or other supporting link)'),
        ),
    ]
