# Generated by Django 5.1.2 on 2026-07-11 00:06

import gallery.models.artworks
import gallery.models.people
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0038_artwork_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.people.artist_image_upload, verbose_name='Profile photo'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.artworks.artwork_image_upload),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(upload_to=gallery.models.artworks.artwork_image_upload),
        ),
    ]
