# Generated by Django 5.1.2 on 2026-07-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0039_site_remove_show_location_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='address',
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State / Province / Region'),
        ),
        migrations.AddField(
            model_name='site',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street address'),
        ),
    ]
