# Generated by Django 5.1.2 on 2026-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0040_site_structured_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small logo or icon for the site (shown in nav and cards).', null=True, upload_to='site_icons'),
        ),
    ]
