# Generated by Django 5.1.2 on 2026-07-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0043_roomconfig_wallplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomconfig',
            name='ceiling_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_textures/'),
        ),
        migrations.AddField(
            model_name='roomconfig',
            name='floor_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_textures/'),
        ),
        migrations.AddField(
            model_name='roomconfig',
            name='wall_e_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_textures/'),
        ),
        migrations.AddField(
            model_name='roomconfig',
            name='wall_n_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_textures/'),
        ),
        migrations.AddField(
            model_name='roomconfig',
            name='wall_s_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_textures/'),
        ),
        migrations.AddField(
            model_name='roomconfig',
            name='wall_w_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_textures/'),
        ),
    ]
