# Generated by Django 5.1.2 on 2026-07-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0044_room_wall_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallObstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West'), ('ceiling', 'Ceiling'), ('floor', 'Floor')], max_length=8)),
                ('label', models.CharField(default='Obstacle', max_length=100)),
                ('x_in', models.FloatField(default=0)),
                ('y_in', models.FloatField(default=42)),
                ('z_in', models.FloatField(default=0)),
                ('w_in', models.FloatField(default=36)),
                ('h_in', models.FloatField(default=80)),
                ('room_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacles', to='gallery.roomconfig')),
            ],
            options={
                'ordering': ['wall', 'x_in', 'z_in'],
            },
        ),
    ]
