# Generated by Django 5.1.2 on 2026-07-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0045_wall_obstacles'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworksubmission',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
