# Generated by Django 5.1.2 on 2026-07-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0046_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallplacement',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
