# Generated by Django 5.1.2 on 2026-07-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0047_wallplacement_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallplacement',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
