# Generated by Django 5.1.2 on 2026-07-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0048_wallplacement_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dropoff', 'Drop-off'), ('pickup', 'Pickup')], max_length=8)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_windows', to='gallery.show')),
            ],
            options={
                'ordering': ['date', 'start'],
            },
        ),
        migrations.CreateModel(
            name='ArtistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dropoff', 'Drop-off'), ('pickup', 'Pickup')], max_length=8)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gallery.artist')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_schedules', to='gallery.show')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='gallery.schedulewindow')),
            ],
            options={
                'unique_together': {('show', 'artist', 'kind')},
            },
        ),
    ]
