# Generated by Django 5.1.2 on 2026-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0049_schedulewindow_artistschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='self_install',
            field=models.BooleanField(default=True, help_text='On: artists schedule an install time (which is also their drop-off). Off: artists schedule a drop-off and the curator installs.', verbose_name='Artists install their own work'),
        ),
        migrations.AlterField(
            model_name='artistschedule',
            name='kind',
            field=models.CharField(choices=[('dropoff', 'Drop-off'), ('install', 'Install'), ('pickup', 'Pickup')], max_length=8),
        ),
        migrations.AlterField(
            model_name='schedulewindow',
            name='kind',
            field=models.CharField(choices=[('dropoff', 'Drop-off'), ('install', 'Install'), ('pickup', 'Pickup')], max_length=8),
        ),
    ]
