# Generated by Django 5.1.2 on 2026-07-15 16:55

import gallery.models.artworks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0050_show_self_install_alter_artistschedule_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='layout_image',
            field=models.ImageField(blank=True, help_text='A cropped image of just the artwork, used in the room layout and 3D view. Best matched to the piece’s proportions. Defaults to the main image if left blank.', null=True, upload_to=gallery.models.artworks.artwork_image_upload, verbose_name='Layout / 3D image (optional)'),
        ),
    ]
