# Generated by Django 5.1.2 on 2026-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0051_artwork_layout_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworksubmission',
            name='curator_decision',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='undecided', max_length=20),
        ),
    ]
