# Generated by Django 5.1.2 on 2026-07-16 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0052_alter_artworksubmission_curator_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-created_at'], name='gallery_art_created_56d51b_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['-created_at'], name='gallery_art_created_572561_idx'),
        ),
        migrations.AddIndex(
            model_name='artworksubmission',
            index=models.Index(fields=['show', 'curator_decision'], name='gallery_art_show_id_2bab61_idx'),
        ),
        migrations.AddIndex(
            model_name='artworksubmission',
            index=models.Index(fields=['show', 'status'], name='gallery_art_show_id_bf133b_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['-start'], name='gallery_sho_start_deeae1_idx'),
        ),
    ]
