# Generated by Django 5.1.2 on 2026-07-18 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0053_artist_gallery_art_created_56d51b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pedestal', 'Pedestal'), ('shelf', 'Shelf')], default='pedestal', max_length=12)),
                ('wall', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West'), ('ceiling', 'Ceiling'), ('floor', 'Floor')], max_length=8)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('x_in', models.FloatField(default=0)),
                ('y_in', models.FloatField(default=0)),
                ('z_in', models.FloatField(default=0)),
                ('w_in', models.FloatField(default=16)),
                ('h_in', models.FloatField(default=40)),
                ('d_in', models.FloatField(default=16)),
                ('rotation', models.IntegerField(default=0)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='gallery.show')),
            ],
            options={
                'ordering': ['wall', 'x_in'],
            },
        ),
        migrations.AddField(
            model_name='wallplacement',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='gallery.support'),
        ),
    ]
