# Generated by Django 5.1.2 on 2026-07-18 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0054_support_wallplacement_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pedestal', 'Pedestal'), ('shelf', 'Shelf')], default='pedestal', max_length=12)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('w_in', models.FloatField(default=16)),
                ('h_in', models.FloatField(default=40)),
                ('d_in', models.FloatField(default=16)),
                ('room_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='gallery.roomconfig')),
            ],
            options={
                'ordering': ['label', 'kind'],
            },
        ),
    ]
