# Generated by Django 5.1.2 on 2026-07-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0055_sitesupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesupport',
            options={'ordering': ['label']},
        ),
        migrations.RemoveField(
            model_name='sitesupport',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='support',
            name='kind',
        ),
    ]
