# Generated by Django 5.1.2 on 2026-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0056_alter_sitesupport_options_remove_sitesupport_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesupport',
            name='texture',
            field=models.ImageField(blank=True, null=True, upload_to='support_textures/'),
        ),
        migrations.AddField(
            model_name='support',
            name='texture_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
