# Generated by Django 5.1.2 on 2026-07-19 04:29

from django.db import migrations, models
from django.db.models import F


def backfill_sent(apps, schema_editor):
    # Existing invitations were emailed when created (old inline-send behavior),
    # so mark them sent to avoid re-emailing everyone on the next Save & Send.
    ShowInvitation = apps.get_model('gallery', 'ShowInvitation')
    ShowInvitation.objects.filter(email_sent_at__isnull=True).update(email_sent_at=F('sent_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0057_sitesupport_texture_support_texture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinvitation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_sent, migrations.RunPython.noop),
    ]
