# Generated by Django 5.1.15 on 2026-07-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0059_showinvitation_token_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='max_submissions_per_artist',
            field=models.PositiveIntegerField(blank=True, help_text='Most artworks each artist may submit to this show. Leave blank for no limit.', null=True, verbose_name='Max submissions per artist'),
        ),
    ]
