# Generated by Django 5.1.15 on 2026-07-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0060_show_max_submissions_per_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='hang_drop_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from the bottom edge of the piece up to the hanging point (wire pulled taut, or hook). Measure once; the layout Hang Info then shows the exact screw-hole height.', max_digits=8, null=True, verbose_name='Hang drop (inches)'),
        ),
    ]
