# Generated by Django 5.1.15 on 2026-07-23 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0061_artwork_hang_drop_inches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowLayoutSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('kind', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_snapshots', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_snapshots', to='gallery.show')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['show', 'kind', '-created_at'], name='gallery_sho_show_id_1d4bfd_idx')],
            },
        ),
    ]
