# Generated by Django 5.1.15 on 2026-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0062_showlayoutsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='framed_depth_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Framed depth (inches)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='framed_height_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Framed height (inches)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='framed_width_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Framed width (inches)'),
        ),
    ]
