# Generated by Django 5.1.15 on 2026-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0063_artwork_framed_depth_inches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomconfig',
            name='initial_camera',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
