# Generated by Django 5.1.15 on 2026-07-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0064_roomconfig_initial_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='replacement_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Replacement value: what the artist is paid if the piece is lost, stolen or damaged in our care'),
        ),
    ]
