# Generated by Django 5.1.15 on 2026-07-29 05:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0065_replacement_value_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='artist',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='State / province'),
        ),
        migrations.AddField(
            model_name='artist',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ZIP / postal code'),
        ),
    ]
