# Generated by Django 5.1.15 on 2026-07-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0066_artist_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='submission_scope',
            field=models.CharField(choices=[('local', 'Local — artists in the venue’s area'), ('national', 'National — artists in the venue’s country'), ('anywhere', 'Anywhere — no location check')], default='local', help_text='Submissions from outside this are flagged for the curator on the Submissions page. Nobody is ever blocked from submitting.', max_length=16, verbose_name='Where artists may be based'),
        ),
        migrations.AddField(
            model_name='site',
            name='submission_area_label',
            field=models.CharField(blank=True, default='', help_text='How the area is described to a curator, e.g. "Bay Area (9 counties)".', max_length=120, verbose_name='Local area name'),
        ),
        migrations.AddField(
            model_name='site',
            name='submission_zipcodes',
            field=models.TextField(blank=True, default='', help_text='Postal codes counting as local to this venue, separated by spaces, commas or newlines. Leave blank to disable area checking. Generated by `manage.py set_site_catchment`.', verbose_name='Local postal codes'),
        ),
    ]
