# The public info pages move from hard-coded templates into the Site row. All additive
# and all blank-defaulted, so applying this changes nothing a visitor sees; 0070 carries
# 120710's existing wording across.

# Generated by Django 5.1.15 on 2026-07-29 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0068_site_country_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktreeentry',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a link that should appear for every site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_tree_entries', to='gallery.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='about',
            field=models.TextField(blank=True, default='', help_text='The Info page: mission, story, people. Accepts formatting, headings, tables and images.'),
        ),
        migrations.AddField(
            model_name='site',
            name='hours',
            field=models.CharField(blank=True, default='', help_text='Shown on the Visit and Contact pages, e.g. "Sun 1-4p or by Appt MWF 12-6p".', max_length=255, verbose_name='Opening hours'),
        ),
        migrations.AddField(
            model_name='site',
            name='visit_image',
            field=models.ImageField(blank=True, help_text='A street view or storefront photo for the Visit page.', null=True, upload_to='site_visit', verbose_name='Visit photo'),
        ),
        migrations.AddField(
            model_name='site',
            name='visit_notes',
            field=models.TextField(blank=True, default='', help_text='Parking, transit and directions, shown on the Visit page below the address.', verbose_name='Getting here'),
        ),
    ]
