# Generated by Django 5.1.15 on 2026-07-29 23:03

import gallery.models.sites
from django.db import migrations, models


def derive(apps, schema_editor):
    """Fill each venue's zone from its address where the state settles it.

    Uses the same helper the model uses on save, so the backfill and every future edit agree.
    A venue in a split state stays blank on purpose: the feed falls back to the gallery's own
    zone, and the form asks rather than guessing an hour wrong.
    """
    from gallery.models.sites import timezone_from_address

    Site = apps.get_model('gallery', 'Site')
    for site in Site.objects.all():
        if site.timezone:
            continue
        derived = timezone_from_address(site.state, site.country)
        if derived:
            site.timezone = derived
            site.save(update_fields=['timezone'])


def clear(apps, schema_editor):
    apps.get_model('gallery', 'Site').objects.update(timezone='')


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0070_seed_120710_public_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA name for the venue’s local time, e.g. America/Los_Angeles. Used to publish event times correctly in the calendar feed. Filled in from the state when that settles it; set it by hand otherwise.', max_length=64, validators=[gallery.models.sites.validate_timezone], verbose_name='Time zone'),
        ),
        migrations.RunPython(derive, clear),
    ]
