# Generated by Django 5.1.15 on 2026-07-30 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0071_site_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='resend_audience_id',
            field=models.CharField(blank=True, default='', help_text='The venue’s own mailing list in Resend. Leave blank to use the network-wide list.', max_length=64, verbose_name='Resend audience ID'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('preheader', models.CharField(blank=True, default='', help_text='The line inboxes show after the subject. Around 90 characters.', max_length=255, verbose_name='Preview text')),
                ('body_markdown', models.TextField(blank=True, default='', help_text='For a one-off. Leave blank if this campaign uses a template.', verbose_name='Body (Markdown)')),
                ('template_name', models.CharField(blank=True, default='', help_text='For a recurring shape: an MJML template under templates/email/campaigns/, e.g. "open_call.mjml". Takes precedence over the Markdown body.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('test_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='Whose subscribers this goes to. Blank for the network-wide list.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='gallery.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('subscribe_form', 'Subscribe form'), ('kiosk', 'Kiosk form'), ('artist_profile', 'Artist profile'), ('import', 'Imported'), ('manual', 'Added by hand')], default='subscribe_form', max_length=32)),
                ('unsubscribed_reason', models.CharField(blank=True, choices=[('requested', 'Unsubscribed'), ('bounced', 'Hard bounce'), ('complained', 'Spam complaint')], default='', max_length=16)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, help_text='Blank for the network-wide list.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gallery.site')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gallery.subscriber')),
            ],
            options={
                'ordering': ['site__name', 'subscriber__email'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'site'), name='unique_subscription_per_site'), models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('subscriber',), name='unique_network_subscription')],
            },
        ),
    ]
