# Generated by Django 5.1.15 on 2026-07-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0072_subscribers_and_campaigns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='resend_audience_id',
        ),
    ]
