# Generated by Django 5.1.15 on 2026-07-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0073_remove_site_resend_audience_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CampaignDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='gallery.campaign')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='gallery.subscription')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'subscription'], name='gallery_cam_campaig_1c52f3_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'subscription'), name='unique_delivery_per_campaign')],
            },
        ),
    ]
