# Generated by Django 5.1.15 on 2026-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0074_campaign_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndelivery',
            name='error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaigndelivery',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('rejected', 'Rejected')], default='sent', max_length=16),
        ),
    ]
