# Generated by Django 5.1.15 on 2026-07-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0076_campaign_paused_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='show',
            field=models.ForeignKey(blank=True, help_text='Required by the show templates. They take the dates, description, artworks and event times from it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='gallery.show'),
        ),
    ]
