# Generated by Django 5.1.15 on 2026-07-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0077_campaign_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndelivery',
            name='outcome',
            field=models.CharField(blank=True, choices=[('bounced', 'Bounced'), ('complained', 'Marked as spam')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='campaigndelivery',
            name='outcome_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
