# Generated by Django 5.1.15 on 2026-07-31 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0078_campaign_delivery_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Inclusive — the last day closed.')),
                ('note', models.CharField(blank=True, default='', help_text='Shown to visitors, e.g. "Between shows".', max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='gallery.site')),
            ],
            options={
                'verbose_name_plural': 'closures',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('by_appointment', models.BooleanField(default=False, help_text='Not open to the public at this time, but visits can be arranged. Left out of what search engines are told, and offered by the visit scheduler.', verbose_name='By appointment only')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='gallery.site')),
            ],
            options={
                'verbose_name_plural': 'opening hours',
                'ordering': ['weekday', 'start'],
                'constraints': [models.UniqueConstraint(fields=('site', 'weekday', 'start', 'end'), name='unique_opening_block')],
            },
        ),
    ]
