# Generated by Django 5.1.15 on 2026-07-31 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0079_structured_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='visit_capacity',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for no limit. Visits share a slot on purpose; this is only a ceiling.', verbose_name='People per slot'),
        ),
        migrations.AddField(
            model_name='site',
            name='visit_horizon_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Book up to (days ahead)'),
        ),
        migrations.AddField(
            model_name='site',
            name='visit_lead_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Slots sooner than this are not offered.', verbose_name='Notice required (hours)'),
        ),
        migrations.AddField(
            model_name='site',
            name='visit_slot_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Slot length (minutes)'),
        ),
        migrations.AddField(
            model_name='site',
            name='visits_enabled',
            field=models.BooleanField(default=False, help_text='Needs opening hours entered below. Visitors pick a slot and you get a calendar invitation by email.', verbose_name='Let visitors book a time'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('minutes', models.PositiveSmallIntegerField(default=30)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gallery.site')),
            ],
            options={
                'ordering': ['when'],
                'indexes': [models.Index(fields=['site', 'when'], name='gallery_vis_site_id_a8c4f8_idx')],
            },
        ),
    ]
