# Generated by Django 5.1.15 on 2026-07-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0080_visit_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteclosure',
            name='appointments_only',
            field=models.BooleanField(default=False, help_text='Tick if the usual public hours still run and it is only appointments that cannot happen — for example you are away but somebody is covering Sunday.', verbose_name='Only closed for appointments'),
        ),
    ]
