# Generated by Django 5.1.15 on 2026-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0081_closure_appointments_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='arrival_note',
            field=models.CharField(blank=True, default='', help_text='What to do when they get here, e.g. "Ring the bell". Sent with every visit confirmation. Distinct from "Getting here", which is about the journey.', max_length=255, verbose_name='On arrival'),
        ),
    ]
