# Generated by Django 5.1.15 on 2026-07-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0082_site_arrival_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='visit_feed_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
