# Generated by Django 5.1.15 on 2026-07-31 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0083_visit_feed_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('response', models.CharField(choices=[('yes', 'Coming'), ('maybe', 'Maybe'), ('no', "Can't make it")], default='yes', max_length=8)),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True, default='')),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='gallery.event')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event', 'response'], name='gallery_eve_event_i_11858b_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='one_rsvp_per_email')],
            },
        ),
    ]
