# Generated by Django 5.1.15 on 2026-07-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0084_event_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.CharField(blank=True, default='', help_text='Everyone on the list, unless you narrow it.', max_length=16, verbose_name='Send to'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_collector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_funder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['is_artist', 'is_collector', 'is_funder'], name='gallery_sub_is_arti_c4725a_idx'),
        ),
    ]
