# Generated by Django 5.1.15 on 2026-08-03 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0085_campaign_segment_subscriber_is_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='directors',
            field=models.ManyToManyField(blank=True, help_text='Can create and run shows at this venue, and manage the artists and artworks in them. Cannot touch other venues, add other directors, or send campaigns.', related_name='directed_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
