# Generated by Django 5.1.15 on 2026-08-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0086_artist_created_by_site_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinvitation',
            name='nudged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
