# Generated by Django 5.1.15 on 2026-08-05 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0087_showinvitation_nudged_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_represented',
            field=models.BooleanField(blank=True, null=True, verbose_name='Represented by a gallery?'),
        ),
        migrations.AddField(
            model_name='artist',
            name='representing_gallery',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Gallery name'),
        ),
        migrations.AddField(
            model_name='show',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the venue’s usual rate. Set it only for a show on different terms, such as a benefit.', max_digits=5, null=True, verbose_name='Commission (%) for this show'),
        ),
        migrations.AddField(
            model_name='site',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of the sale price this venue keeps. Used in consignment agreements. Leave blank if it has not been decided — agreements will not generate until it has.', max_digits=5, null=True, verbose_name='Commission (%)'),
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Not yet signed'), ('signed', 'Signed'), ('superseded', 'Superseded by a later version')], default='draft', max_length=20)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terms_version', models.PositiveSmallIntegerField(default=1)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_name', models.CharField(blank=True, default='', max_length=255)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='gallery.artist')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='gallery.show')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['show', 'status'], name='gallery_con_show_id_c23aaf_idx')],
                'constraints': [models.UniqueConstraint(fields=('show', 'artist', 'version'), name='one_consignment_version_per_artist_show')],
            },
        ),
    ]
