# Generated by Django 5.1.15 on 2026-08-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0088_artist_is_represented_artist_representing_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='custody_grace_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='After the last pickup time, how many days the venue remains responsible for work that has not been collected. Stated in every consignment agreement. After it, uncollected work is held at the artist’s risk.', verbose_name='Days we stay responsible after pickup closes'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='terms_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
