# Generated by Django 5.1.15 on 2026-08-05 02:57

from django.db import migrations, models


def carry_values_over(apps, schema_editor):
    """Copy replacement_cost into agreed_value. Same number, better name.

    Add-and-backfill rather than a rename: Railway runs migrations in pre-deploy while the
    *old* code is still serving, and old code selecting a column that no longer exists 500s
    every artwork page for the length of the deploy. The old column is dropped in a later
    one. See docs/railway-deploys.md.
    """
    Artwork = apps.get_model('gallery', 'Artwork')
    Artwork.objects.filter(replacement_cost__isnull=False).update(
        agreed_value=models.F('replacement_cost'))


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0089_site_custody_grace_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='agreed_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Agreed value: what the artist is paid if the piece is lost, stolen or damaged in our care'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='replacement_cost',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(carry_values_over, migrations.RunPython.noop),
    ]
