# Generated by Django 5.1.15 on 2026-08-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0090_artwork_agreed_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='terms_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
