# Generated by Django 5.1.15 on 2026-08-05 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0091_consignment_terms_version_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='consignment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Not yet signed'), ('signed', 'Signed'), ('superseded', 'Superseded by a later version'), ('voided', 'Voided by the gallery')], default='draft', max_length=20),
        ),
    ]
