# Generated by Django 5.1.15 on 2026-08-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0092_consignment_voided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='gallery.artist'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='gallery.show'),
        ),
    ]
