# Generated by Django 5.1.15 on 2026-08-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0093_consignment_protect_signed_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_at', models.DateTimeField()),
                ('sent_count', models.PositiveSmallIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_requests', to='gallery.artist')),
                ('last_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_requests', to='gallery.show')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('show', 'artist'), name='one_consignment_request_per_artist_show')],
            },
        ),
    ]
