# Generated by Django 5.1.15 on 2026-08-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0094_consignment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='signed_capacity',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Signing as, if not the artist'),
        ),
        migrations.AddField(
            model_name='site',
            name='introduction_tail_days',
            field=models.PositiveSmallIntegerField(default=60, help_text='If the gallery introduced a buyer during the show, a sale to that buyer within this many days of the work going home still pays commission. Sales to anyone else never do. 0 waives it.', verbose_name='Days we can claim commission on a buyer we introduced'),
        ),
    ]
