# Generated by Django 5.1.15 on 2026-08-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0096_artwork_create_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='create_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
