"""Per-step screenshots for the how-to guides.

Screenshots are treated as **compiled assets, not documents**: nothing about them is
recorded in `role_docs.py`, and no step is edited to point at an image. They are
generated by `manage.py capture_howto`, published to their own S3 prefix, and described
by one small committed manifest. See `docs/visual-howto-documentation.md`.

## Why a manifest, and not a directory listing

The images themselves are not in git — ~110 KB each, regenerated wholesale, tens of
megabytes at full coverage. So the help page cannot stat a directory to learn what
exists, and in particular cannot read each file's pixel dimensions, which is what the
1:1 sizing below depends on. Asking S3 per render is a network call per image.

`HOWTO_MANIFEST_PATH` therefore holds step number → object key plus dimensions, a few KB
of JSON. It is generated, never hand-edited, and it is the single source of truth in
production. It also makes a capture reviewable: a diff shows which guides' screenshots
moved, which a directory of binaries never did.

Serving needs only `settings.HOWTO_IMAGE_BASE_URL` — no boto3, no credentials.

## Local staging

`capture_howto` also writes plain unhashed files under `static/img/howto/<key>/NN.webp`,
which is gitignored. In DEBUG those win over the manifest, so a capture is visible on the
next reload without publishing anything. Production never looks at them.

## Image keys

In order of preference:

    guide['image_key']  →  guide['anchor']  →  slugify(guide['title'])

Deliberately *not* the title, which gets reworded — that would orphan every image under
the old slug, the same failure mode stable `'anchor'` keys prevent for `#howto` links.
`image_key` exists because anchors are *not* unique: the two submit-artwork guides
deliberately share one anchor so a single link serves either reader, but their steps
differ in content and order, so step 3 of one is not step 3 of the other. Sharing a key
would caption one guide with the other's screenshots.
`gallery/tests.py::HowToImageKeyTests` enforces uniqueness.

## Legibility

This is a sizing problem, not a resolution one. Captures are taken at a device scale
factor of HOWTO_CAPTURE_SCALE, so a file is that many times larger than the region the
reader saw. `steps_with_images` divides back down and hands the template explicit
`width`/`height`, so every screenshot renders at exactly its browser size — never shrunk
to fit a column, which is what turns form labels to mush — while keeping spare pixels for
retina. Keeping a shot legible is therefore mostly `capture_howto`'s job: crop to the
region the step is about, so 1:1 is small enough to fit.
"""
import json
from pathlib import Path

from django.conf import settings
from django.utils.text import slugify

# Local staging area (gitignored), relative to a static root.
HOWTO_IMAGE_SUBDIR = Path('img') / 'howto'

# WebP is what capture_howto writes: a browser screenshot is mostly flat colour and
# large, and WebP holds it at roughly a tenth of the equivalent PNG — 872 KB per guide
# rather than 14 MB. PNG is still read so a hand-made image can be dropped in.
HOWTO_IMAGE_FORMATS = ('png', 'webp')

# Device pixel ratio captures are taken at. Shared with capture_howto so the division
# here and the multiplication there cannot drift apart.
HOWTO_CAPTURE_SCALE = 2

HOWTO_MANIFEST_PATH = Path(__file__).resolve().parent / 'howto_manifest.json'

# Guide key -> {step: {...}}. The help page renders ~30 guides of ~8 steps each; without
# this it would re-read the manifest and stat/open staging files hundreds of times per
# request. Not used when DEBUG, so a capture shows up on the next reload.
_scan_cache = {}
_manifest_cache = None


def image_key(guide):
    """The key a guide's screenshots are stored under. See module docstring."""
    return guide.get('image_key') or guide.get('anchor') or slugify(guide['title'])


def staging_dir(key):
    """Where `capture_howto` writes before publishing, and what DEBUG prefers.

    STATICFILES_DIRS[0] so DEBUG can serve it without collectstatic. Gitignored.
    """
    return Path(settings.STATICFILES_DIRS[0]) / HOWTO_IMAGE_SUBDIR / key


def step_filename(step_number, ext='webp'):
    """1-based step number -> "07.webp". Zero-padded so `ls` sorts correctly."""
    return f'{step_number:02d}.{ext}'


def load_manifest():
    """The published manifest: {image key: {step number (str): entry}}."""
    global _manifest_cache
    if _manifest_cache is not None and not settings.DEBUG:
        return _manifest_cache
    try:
        with open(HOWTO_MANIFEST_PATH) as fh:
            manifest = json.load(fh)
    except (OSError, ValueError):
        # Absent or corrupt: the guides still read fine as prose. A missing manifest is
        # the normal state for a checkout that has never published.
        manifest = {}
    _manifest_cache = manifest
    return manifest


def save_manifest(manifest):
    """Write the manifest back, sorted and newline-terminated so diffs stay small."""
    global _manifest_cache
    with open(HOWTO_MANIFEST_PATH, 'w') as fh:
        json.dump(manifest, fh, indent=2, sort_keys=True)
        fh.write('\n')
    _manifest_cache = None
    _scan_cache.clear()


def _measure(path):
    """(width, height) in CSS pixels — the size this region had in the browser."""
    from PIL import Image
    try:
        with Image.open(path) as img:
            width, height = img.size
    except OSError:
        return None
    return (max(1, round(width / HOWTO_CAPTURE_SCALE)),
            max(1, round(height / HOWTO_CAPTURE_SCALE)))


def _from_staging(key):
    """Locally captured but unpublished images, for DEBUG preview."""
    directory = staging_dir(key)
    if not directory.is_dir():
        return {}
    from django.templatetags.static import static

    found = {}
    # In HOWTO_IMAGE_FORMATS order, so when both exist the last listed wins — WebP.
    for ext in HOWTO_IMAGE_FORMATS:
        for path in sorted(directory.glob(f'[0-9][0-9].{ext}')):
            size = _measure(path)
            if size is None:
                continue
            relative = (HOWTO_IMAGE_SUBDIR / key / path.name).as_posix()
            try:
                url = static(relative)
            except ValueError:
                continue
            found[int(path.stem)] = {
                'url': url, 'width': size[0], 'height': size[1], 'staged': True}
    return found


def _from_manifest(key):
    """Published images, resolved against HOWTO_IMAGE_BASE_URL."""
    base = getattr(settings, 'HOWTO_IMAGE_BASE_URL', None)
    if not base:
        return {}
    found = {}
    for number, entry in load_manifest().get(key, {}).items():
        object_key = entry.get('key')
        if not object_key:
            continue
        found[int(number)] = {
            'url': base + object_key,
            'width': entry.get('width'),
            'height': entry.get('height'),
            'staged': False,
        }
    return found


def _images_for(key):
    """Published images, with locally staged ones taking precedence in DEBUG."""
    images = _from_manifest(key)
    if settings.DEBUG:
        images.update(_from_staging(key))
    return images


def _cached_images_for(key):
    if settings.DEBUG:
        return _images_for(key)
    if key not in _scan_cache:
        _scan_cache[key] = _images_for(key)
    return _scan_cache[key]


def steps_with_images(guide):
    """[{'text', 'image', 'width', 'height'}] — one entry per step, in order.

    `guide['steps']` is left untouched: it is still a plain list of strings, which the
    help page's "Walk me through it" widget needs for its `|||`-joined `data-steps`
    attribute, and which every existing reader of HOW_TO_GUIDES expects.
    """
    images = _cached_images_for(image_key(guide))
    steps = []
    for number, text in enumerate(guide['steps'], start=1):
        found = images.get(number) or {}
        steps.append({
            'text': text,
            'image': found.get('url'),
            'width': found.get('width'),
            'height': found.get('height'),
        })
    return steps
