HOW_TO_GUIDES = [
    {
        'title': 'How to sign up for an account',
        'roles': None,
        'steps': [
            'Open the Account menu in the navigation and choose Sign Up.',
            'Enter your first name, last name, email address, and password — or use the "Continue with Google" option to skip the password. There is no separate username; your email address is how you log in.',
            'After signing up, an artist profile is automatically created for you using your name and email. If your email matches an existing artist record you were added under, the link is made for you automatically.',
            'If you were added under a different email, visit your artist edit page after signing in — you will see a link to claim your existing record. See "Linking your account to an existing artist profile" in the how-to guides for full details.',
        ],
    },
    {
        'title': 'How to complete your artist profile',
        'roles': {'artist', 'curator', 'juror', 'staff'},
        'steps': [
            'After signing up you are taken directly to your artist profile edit page — fill in your details there.',
            'If you need to return to your profile later, sign in — you will be taken to your Me page. Click Edit on your artist profile.',
            'Fill in your bio, statement, website, Instagram handle, Venmo, and upload a profile photo.',
            'The email on your artist record is your public contact address (used for invitations and curator communication). It can be different from your login email. Update it on the edit page if needed.',
            'Your profile becomes publicly visible once you are part of a show whose status is Published or Closed, or once a staff member adds you as a curator of a show.',
        ],
    },
    {
        'title': 'How to add artworks',
        'roles': {'artist', 'curator', 'juror', 'staff'},
        'steps': [
            'Sign in — you will be taken to your Me page. Find the Artworks section and click the New button.',
            'Fill in the title, year, medium, dimensions (width × height × depth), and upload an image — image is required for new artworks.',
            'Optionally set the pricing type (For Sale, Price on Request, Best Offer, or Not For Sale), add a price if applicable, set a replacement cost, and add a description.',
            'Newly added artworks are private until they are included in a show whose status is Published or Closed.',
        ],
    },
    {
        'title': 'How to submit artwork to an open call show',
        'roles': {'artist', 'curator', 'juror', 'staff'},
        'steps': [
            'Sign in — you will be taken to your Me page. Find the show you want to submit to under "Shows Accepting Submissions" and click the Submit button.',
            'Select the artwork you want to submit from the dropdown. Each artwork can only be submitted once per show.',
            'Click Submit to confirm.',
            'You will receive a confirmation email. Your submission appears on your Me page and on the show detail page as "Submitted".',
            'You can retract your submission while the show is still accepting submissions by clicking Retract next to your artwork on your Me page or the show detail page.',
            'Once the show moves to In Review, submissions are closed and you cannot retract.',
            'You will receive an acceptance or rejection email when the curator publishes the show.',
        ],
    },
    {
        'title': 'How to create a show (staff only)',
        'roles': {'staff'},
        'steps': [
            'Sign in as a staff user, then go to Shows in the navigation.',
            'Click New at the top of the Shows page.',
            'Enter the show name, dates, description, and upload a hero image.',
            'Choose a Submission Type: "Open" for a public open call, or "Invited" for an invitation-only show.',
            'Set the Submission Deadline (required), Review Deadline (when jurors must finish scoring), and Decision Date (when artists will be notified — informational only).',
            'To assign a curator, add them in the Curators field — only artists with linked user accounts appear in this list.',
            'New shows start with status "Under Consideration" — they are private and only visible to staff, curators, and jurors.',
            'Save the show. The curator can then edit the show and advance it through the lifecycle.',
        ],
    },
    {
        'title': 'Show lifecycle and status',
        'roles': {'curator', 'staff'},
        'steps': [
            'Every show has a status that controls who can see it and what actions are available.',
            'Change the status using the → button shown next to the current status on the show detail page (visible to curators and staff only).',
            'Under Consideration — private. Use this while planning. Only staff, curators, and jurors can see the show.',
            'Open Call — public. Invited artists (or everyone, for open shows) can submit work. Displays an "Open Call" or "Invitation Only" badge. Set this when you are ready to accept submissions.',
            'In Review — public (open shows only). Submissions are closed. Jurors score submitted artworks. Setting this status automatically emails all assigned jurors.',
            'Draft — private. Use this to assemble and curate the show privately before publishing.',
            'Published — public. The show is live. Setting this redirects to the Publish page where you confirm which artworks to include and sends acceptance/rejection emails to all submitting artists.',
            'Closed — public. The show has ended. It remains visible but indicates the run is complete.',
            'Staff and curators can always see shows in all statuses. Jurors can also see all shows regardless of status.',
        ],
    },
    {
        'title': 'How to run an invitation-only show',
        'roles': {'curator', 'staff'},
        'steps': [
            'Create the show (staff only) with Submission Type set to "Invited" and a submission deadline.',
            'On the show detail page, click "Invite Artists" to add artists by email address. Each invited artist will receive an invitation email.',
            'Artists who do not yet have an account can sign up at any time — their invitation is automatically linked when they register with the same email address.',
            'Click → Open Call on the show detail page. Invited artists can now submit their work.',
            'After the submission deadline, click → Draft on the show detail page to close submissions.',
            'Go to the Reviews page. Use the Curation Slideshow button in the Artworks section to sort submissions into Selected, Rejected, or Undecided — artworks are sorted highest score first with juror scores visible on the right. Decisions save instantly. Alternatively, use the dropdowns on the Submissions page.',
            'When your selections are final, click → Published on the show detail page. This redirects to the Publish Show confirmation page.',
            'Review the diff and click "Confirm & Publish Show". This adds all Selected artworks to the show, sets the status to Published, and sends acceptance/rejection emails to every submitting artist.',
            'Set status to Closed when the show run ends.',
            'Optionally add events (openings, talks) from the Events section.',
        ],
    },
    {
        'title': 'How to run an open call show',
        'roles': {'curator', 'staff'},
        'steps': [
            'A staff member creates the show with Submission Type set to "Open" and a submission deadline. As curator you can then edit the show name, dates, description, and hero image.',
            'On the show detail page, click → Open Call next to the status. The show is now public and artists can submit work.',
            'Optionally define a rubric (weighted scoring criteria) from the Reviews page. Click "Manage Rubric Criteria" to add, edit, or remove criteria. If a previous show already has the rubric you want, use the "Copy rubric from another show" dropdown on that page to import it in one step — existing criteria are replaced.',
            'Optionally assign jurors now via Assign Jurors on the show detail page, or wait until after submissions close.',
            'Artists submit their work via the show detail page. You can monitor submissions at any time via Submissions on the show detail page.',
            'When the submission period ends, click → In Review on the show detail page. Submissions are now closed and all assigned jurors are emailed automatically.',
            'Jurors score each submitted artwork. Monitor progress and view aggregated scores on the Reviews dashboard.',
            'Click → Draft on the show detail page. This closes the review phase and lets you work privately.',
            'Go to the Reviews page. Use the Curation Slideshow button in the Artworks section to sort submissions into Selected, Rejected, or Undecided — artworks are sorted highest score first, and each juror\'s scores are shown on the right. Decisions save instantly. Alternatively, use the dropdowns on the Submissions page.',
            'When your selections are final, click → Published on the show detail page. This redirects to the Publish Show confirmation page showing what will be added and removed.',
            'Review the diff and click "Confirm & Publish Show". In one step this adds all Selected artworks and their artists to the show, sets the status to Published, and sends acceptance/rejection emails to every submitting artist.',
            'Click → Closed on the show detail page when the show run ends.',
        ],
    },
    {
        'title': 'How to run a public art site open call',
        'roles': {'curator', 'staff'},
        'steps': [
            'Create the show with show_type set to "Public Art Site" and enter the site location in the Location field.',
            'Set Submission Type to "Open" (or "Invited") and set a submission deadline as you would for a regular open call.',
            'The show will display a "Public Art" badge on its card and detail page.',
            'All other open call steps (status transitions, submissions, jury, promote) work the same as a gallery open call.',
        ],
    },
    {
        'title': 'How to jury a show',
        'roles': {'juror', 'curator', 'staff'},
        'steps': [
            'Make sure you have an account on this site and that your artist profile information is complete — the curator will need to assign you by name.',
            'A curator or staff member assigns you as a juror. You will receive an email when the show moves to In Review status.',
            'Sign in and go to Shows. Open the show you are jurying and click Reviews on the show detail page.',
            'You will see a Pending Review section listing all artworks you have not yet scored. The fastest way to score is the Review Slideshow — see "How to use the Review Slideshow" for step-by-step instructions.',
            'Alternatively, click Review on any individual artwork to score it on its own page.',
            'If the curator has defined a rubric, score each criterion individually. Otherwise rate the artwork overall.',
            'Optionally add review notes. Scores save instantly in the slideshow, or click Submit review on the individual page.',
            'You can return to update your scores at any time before the curator closes the review phase.',
            'Your scores are averaged with other jurors\' scores and shown to the curator on the Reviews dashboard.',
            'If you are also a curator of this show, scroll past the curator overview section on the Reviews page to find your own Pending Review section.',
        ],
    },
    {
        'title': 'How to use the Review Slideshow',
        'roles': {'juror', 'curator', 'staff'},
        'steps': [
            'From the Reviews page for your show, click the "Review Slideshow" button next to the "Pending Review" heading. The slideshow opens full-screen.',
            'The artwork image fills the left side. The right side shows the artwork title, artists (hidden if the show uses blind review), and one scoring button row per rubric criterion.',
            'Click a score button — Weak, Developing, Solid, Strong, or Exceptional — to record your score for that criterion. Your score saves instantly; there is no Submit button.',
            'When all criteria are scored the slideshow automatically advances to the next unscored artwork (if Auto is checked in the top bar). Uncheck Auto to advance manually.',
            'Use "Skip weak" in the top bar to skip over artworks where you have already scored any criterion as Weak. Those artworks get a red thumbnail border. You can still navigate to them directly by clicking their thumbnail.',
            'Use the ← → arrow keys or the on-screen arrows to move between artworks at any time.',
            'Press 1–5 on the keyboard to score the focused criterion (highlighted in the left border). Press Tab to move focus to the next criterion.',
            'Thumbnail strip at the bottom: gold border = partially scored, green border = fully scored, red border = has a Weak score, teal outline = current artwork.',
            'Press Enter or D (or click the ↗ link in the top bar) to open the artwork detail page. If the show uses blind review the detail page opens without artist information.',
            'After viewing the artwork detail, press the browser Back button. The slideshow reopens at the artwork you were on.',
            'Press Esc or click × to close the slideshow at any time. Your scores are already saved.',
            'Press ? for a quick keyboard reference.',
        ],
    },
    {
        'title': 'How to use the Curation Slideshow',
        'roles': {'curator', 'staff'},
        'steps': [
            'From the Reviews page for your show, click the "Curation Slideshow" button next to the "Artworks" heading. The slideshow opens full-screen.',
            'Artworks are presented in order from highest to lowest overall jury score, so the strongest candidates appear first.',
            'The artwork image fills the left side. The right side shows the artwork title, artists (hidden if the show uses blind review), year, medium, and dimensions.',
            'Below the artwork info the right panel shows the jury scores: each juror\'s name, their score on each rubric criterion, and their weighted total. The overall score averaged across all jurors is shown at the top in teal.',
            'Weak scores (the lowest rating) are shown in red so you can spot them at a glance.',
            'At the bottom of the right panel are three decision buttons: Undecided, Selected, and Rejected. Click one to record your decision. It saves instantly and the slideshow advances to the next artwork after a moment.',
            'The top bar shows a running count: Selected, Rejected, and Undecided.',
            'Thumbnail strip at the bottom: green border = selected, red border = rejected, gray border = undecided, teal outline = current artwork.',
            'Use the ← → arrow keys or on-screen arrows to navigate without recording a decision.',
            'Keyboard shortcuts: S = Selected, R = Rejected, U = Undecided, ← → = navigate, Enter or D = open detail page, Esc = close.',
            'Press Enter or D to open the artwork detail page. If the show uses blind review the detail page opens without artist information. Press the browser Back button to return to the slideshow at the same position.',
            'When you are finished, close the slideshow with Esc or ×. Your decisions are already saved. To publish the show, go to the show detail page and follow the standard → Published / Confirm & Publish Show workflow.',
        ],
    },
    {
        'title': 'Linking your account to an existing artist profile',
        'roles': None,
        'steps': [
            'There are three cases — figure out which one applies, then follow the matching steps.',
            'Case 1 — Same email: You were already in the system and you signed up using the same email address that is on your artist record. The system linked your account automatically. No extra steps needed — just fill in your profile.',
            'Case 2 — Different email: You were already in the system but you signed up with a different email than the one on your existing artist record. Sign in, then go to your artist edit page — you will see a link to "link it to your account here". Click it, enter the OLD email address that is on your existing record, and submit. Your blank auto-created profile is replaced with your existing record, preserving all artworks and show history. The artist email is left unchanged (it is your public contact address and may intentionally differ from your login email — you can update it from the edit page if needed).',
            'Case 3 — New to the system: You have no existing record. A new artist profile was created for you automatically when you signed up. Go to your artist profile and fill in your bio, statement, website, Instagram, and upload a profile photo.',
            'Not sure which case applies? Email info@120710.art — a staff member can look up your record, tell you which email is on it, and link it for you if needed.',
        ],
    },
    {
        'title': 'How to submit artwork to an open call show',
        'roles': None,
        'public_only': True,
        'steps': [
            'First, create an artist account — see "How to sign up for an account" above.',
            'Once you are signed in as an artist, return to this help section for detailed submission instructions that will appear here.',
        ],
    },
    {
        'title': 'How to pin artworks',
        'roles': None,
        'steps': [
            'Sign in. Browse any show or the Artworks gallery.',
            'On any artwork card, click the 📌 Pin button in the card footer. The button turns orange and shows "Pinned" to confirm it has been saved.',
            'You can also pin or unpin from within a slideshow — a 📌 button appears in the top bar next to the open-detail link.',
            'Pinned artworks appear on your artist profile page under "Pinned". The section is only visible to you.',
            'To arrange your pinboard, drag and drop the cards into any order — the order saves automatically.',
            'To unpin, click the orange 📌 Pinned button again on the card or artwork detail page.',
        ],
    },
    {
        'title': 'How to record artwork ownership',
        'roles': None,
        'steps': [
            'Sign in. Navigate to the artwork detail page for a piece you own — purchased, received as a gift, or otherwise acquired.',
            'Click "Record ownership". This creates a pending ownership claim and notifies the artwork\'s artist.',
            'The artwork\'s artist sees your claim under "Pending Collection Confirmations" on their profile page and clicks Confirm or Decline. Curators and staff can also confirm claims.',
            'While pending, a yellow "awaiting artist confirmation" badge appears on the artwork detail page.',
            'Once confirmed, a green badge appears and the piece is listed in your Collection on your public artist profile.',
            'From your profile, drag and drop collection cards to arrange them in any order — the order saves automatically.',
            'To remove a piece from your collection at any time, click Remove on the artwork detail page.',
        ],
    },
    {
        'title': 'How to buy a piece of artwork',
        'roles': None,
        'steps': [
            'Find the artwork you are interested in — browse Shows or Artists from the navigation, or ask the gallery for a direct link.',
            'On the artwork detail page, check the price listed. If it shows "Not For Sale" the work is unavailable. If it shows "Price on Request" or "Best Offer", the artist will discuss pricing with you directly.',
            'Click the Inquire button on the artwork page.',
            'Fill in your name, email address, and a message to the artist — for example, express your interest and ask any questions about the work.',
            'Submit the form. Your message is sent directly to the artist with your email address included so they can reply to you.',
            'The artist will follow up with you by email to arrange payment and delivery or pickup.',
        ],
    },
    {
        'title': 'How to link an artist profile to a user (staff only)',
        'roles': {'staff'},
        'steps': [
            'Sign in as a staff user, then go to /accounts/link-artists/.',
            'Select the unlinked artist record from the first dropdown (only artists with no user account appear).',
            'Select the user account to link it to from the second dropdown.',
            'Click Link. The artist record is immediately associated with that user account.',
            'After linking, the user can sign in and manage that artist profile.',
        ],
    },
]

GENERAL_GUIDE = {
    'title': 'Account Basics',
    'summary': 'Use these steps to access your account and keep your profile current.',
    'allowed_actions': [
        'Sign in via Account → Log In in the navigation.',
        'Reset your password from the login page if you have forgotten it.',
        'Change your password via Account → Change Password in the navigation.',
        'Edit and Delete links only appear when your account can manage that record.',
    ],
    'forms': [
        {
            'name': 'Name Profile Form',
            'where_used': 'Account → Profile (/accounts/profile/)',
            'breadcrumb': 'Home > Account > Profile',
            'fields': [
                {
                    'name': 'first_name',
                    'input_type': 'text input',
                    'purpose': 'Your public first name shown throughout the site.',
                },
                {
                    'name': 'last_name',
                    'input_type': 'text input',
                    'purpose': 'Your public last name shown throughout the site.',
                },
            ],
        },
    ],
}


ROLE_DOCUMENTATION = {
    'artist': {
        'title': 'Artist Guide',
        'summary': 'Artists manage their own profile and artworks, and can submit work to open call and invitation-only shows.',
        'allowed_actions': [
            'Create and edit your artist profile.',
            'Create and edit your own artworks.',
            'Submit artworks to open call shows (or invitation-only shows where you have been invited) via the "Shows Accepting Submissions" section on your Me page.',
            'Track your submission statuses and retract submissions from the show detail page while the deadline is open.',
            'Your artworks and profile become publicly visible once you are part of a show whose status is Published or Closed.',
            'If you have an existing artist record that was created before you had an account, check your artist edit page after signing in — a notice will appear if your profile is empty, with a link to claim your existing record by entering the old email.',
            'If you are unsure which email is on your existing record, email info@120710.art and a staff member can look it up or link it for you.',
        ],
        'forms': [
            {
                'name': 'Artist Form',
                'where_used': 'Artist create/edit pages',
                'breadcrumb': 'Me page > Edit, or Artists list > Edit',
                'fields': [
                    {'name': 'first_name', 'input_type': 'text input', 'purpose': 'Given name for your artist profile.'},
                    {'name': 'last_name', 'input_type': 'text input', 'purpose': 'Family name for your artist profile.'},
                    {'name': 'email', 'input_type': 'email input', 'purpose': 'Contact email for curator/admin communication.'},
                    {'name': 'phone', 'input_type': 'text input', 'purpose': 'Optional contact phone number.'},
                    {'name': 'website', 'input_type': 'url/text input', 'purpose': 'External portfolio or personal website URL.'},
                    {'name': 'instagram', 'input_type': 'text input', 'purpose': 'Instagram handle starting with @.'},
                    {'name': 'venmo', 'input_type': 'text input', 'purpose': 'Venmo username starting with @.'},
                    {'name': 'bio', 'input_type': 'multi-line text area', 'purpose': 'Artist biography shown publicly.'},
                    {'name': 'statement', 'input_type': 'multi-line text area', 'purpose': 'Artist statement shown publicly.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Profile photo shown on artist pages.'},
                ],
            },
            {
                'name': 'Artwork Form',
                'where_used': 'Artwork create/edit pages',
                'breadcrumb': 'Me page > Artworks > New, or Artwork Detail > Edit',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Title of the artwork.'},
                    {'name': 'end_year', 'input_type': 'numeric input', 'purpose': 'Year the work was completed (or ending year for multi-year works).'},
                    {'name': 'start_year', 'input_type': 'numeric input', 'purpose': 'Starting year for multi-year works. Leave blank for single-year works.'},
                    {'name': 'medium', 'input_type': 'text input', 'purpose': 'Primary materials or medium.'},
                    {'name': 'width × height × depth', 'input_type': 'numeric inputs', 'purpose': 'Physical dimensions in inches. Depth is optional.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Primary artwork image. Required when creating a new artwork.'},
                    {'name': 'pricing_type', 'input_type': 'dropdown select', 'purpose': 'Pricing type: For Sale (requires a price), Price on Request, Best Offer (optionally set a minimum), or Not For Sale.'},
                    {'name': 'price', 'input_type': 'numeric input', 'purpose': 'Required for For Sale; optional minimum for Best Offer. Hidden for Price on Request and Not For Sale.'},
                    {'name': 'replacement_cost', 'input_type': 'numeric input', 'purpose': 'Insurance or replacement value.'},
                    {'name': 'is_sold', 'input_type': 'checkbox', 'purpose': 'Marks the work as sold.'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Public description of the work.'},
                    {'name': 'installation', 'input_type': 'multi-line text area', 'purpose': 'Display or installation notes for the venue.'},
                ],
            },
            {
                'name': 'Open Call Submission Form',
                'where_used': 'Show detail page when the show is accepting submissions',
                'breadcrumb': 'Home > Shows > Select Show > Submit Artwork',
                'fields': [
                    {'name': 'artwork', 'input_type': 'dropdown select', 'purpose': 'Choose which of your artworks to submit. Each artwork can only be submitted once per show.'},
                ],
            },
        ],
    },
    'curator': {
        'title': 'Curator Guide',
        'summary': 'Curators manage shows and events, control show lifecycle status, run open call and invitation-only workflows, assign jurors, and review aggregated jury ratings.',
        'allowed_actions': [
            'Edit and manage shows and events you are listed as curator for.',
            'See all shows regardless of status (Under Consideration, Draft, and other private statuses are visible to curators).',
            'See all artworks including those not yet in a show.',
            'Advance a show through its lifecycle by changing the Status field on the show edit page.',
            'Run open call shows: set status to Open Call to accept submissions, advance to In Review after the deadline, then select or reject submissions, promote selected artworks, and publish.',
            'Run invitation-only shows: invite artists by email, set status to Open Call so invited artists can submit, then advance to Draft, select or reject, and publish.',
            'Define a weighted rubric for jury scoring: add named criteria with weights from the Manage Rubric Criteria page. Jurors score each criterion; the dashboard shows a weighted composite score per artwork.',
            'Assign artists as jurors for your show from the Reviews page.',
            'View all juror reviews and weighted composite scores per artwork on the Reviews dashboard.',
            'Use the Curation Slideshow to sort submissions into Selected, Rejected, or Undecided. Artworks are shown highest-score first. Scores and per-juror breakdowns are shown on the right. Decisions save instantly.',
            'Edit juror reviews when corrections are needed.',
            'Your artist profile becomes publicly visible when you are added as a curator of a show.',
            'Edit and Delete links appear only for shows and events you are assigned to curate.',
        ],
        'forms': [
            {
                'name': 'Show Form',
                'where_used': 'Show edit pages (curators can edit, staff can create)',
                'breadcrumb': 'Shows > New (staff only) or Show Detail > Edit',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Show title shown in listings and detail pages.'},
                    {'name': 'show_type', 'input_type': 'dropdown select', 'purpose': 'Gallery Show or Public Art Site. Affects the badge shown on the show card.'},
                    {'name': 'location', 'input_type': 'text area', 'purpose': 'Address or site description. Shown on the show detail page for public art sites.'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Public show description.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Hero image for the show.'},
                    {'name': 'status', 'input_type': 'dropdown select', 'purpose': 'Controls the show lifecycle phase and visibility. Under Consideration and Draft are private (staff, curators, jurors only). Open Call, In Review, Published, and Closed are publicly visible. Only curators and staff can change this field.'},
                    {'name': 'submission_type', 'input_type': 'dropdown select', 'purpose': 'Open — any artist can submit when the show is in Open Call status. Invited — only artists who have received an invitation email can submit.'},
                    {'name': 'submission_deadline', 'input_type': 'date input', 'purpose': 'Required. Cutoff date for artist submissions. After this date, manually advance the status to Draft to close submissions.'},
                    {'name': 'review_deadline', 'input_type': 'date input', 'purpose': 'Target date for jurors to finish scoring. Shown to jurors so they know when their reviews are due (informational — does not lock automatically).'},
                    {'name': 'decision_date', 'input_type': 'date input', 'purpose': 'Target date for notifying artists of acceptance/rejection decisions (informational only — does not lock anything automatically).'},
                    {'name': 'start', 'input_type': 'date input', 'purpose': 'Show opening date. Artworks and artists become publicly visible from this date.'},
                    {'name': 'end', 'input_type': 'date input', 'purpose': 'Show closing date.'},
                    {'name': 'tags', 'input_type': 'multi-select', 'purpose': 'Categorization tags for filtering and organization.'},
                    {'name': 'curators', 'input_type': 'multi-select', 'purpose': 'Artists assigned as curators. They gain edit access to the show and become publicly visible.'},
                ],
            },
            {
                'name': 'Curation Slideshow',
                'where_used': 'Reviews page → Artworks section → Curation Slideshow button',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Curation Slideshow',
                'fields': [
                    {'name': 'Selected / Undecided / Rejected', 'input_type': 'click buttons per artwork', 'purpose': 'Record your curation decision. Saves instantly. Keyboard shortcuts: S = Selected, R = Rejected, U = Undecided.'},
                    {'name': 'Jury scores panel', 'input_type': 'read-only display', 'purpose': 'Shows each juror\'s per-criterion scores and weighted total, plus the overall average across all jurors. Weak scores are highlighted in red. Artworks are sorted highest overall score first.'},
                    {'name': '↗ link / Enter / D key', 'input_type': 'navigation', 'purpose': 'Opens the artwork detail page. Respects blind review. Press Back to return to the slideshow at the same position.'},
                    {'name': 'Thumbnail strip', 'input_type': 'read-only display', 'purpose': 'Green border = Selected, red border = Rejected, gray = Undecided. Click any thumbnail to jump directly to that artwork.'},
                ],
            },
            {
                'name': 'Submission Status Form',
                'where_used': 'Open call submissions review page',
                'breadcrumb': 'Home > Shows > Select Show > Submissions',
                'fields': [
                    {'name': 'status per row', 'input_type': 'dropdown select per row', 'purpose': 'Set each submission to Submitted, Selected, or Rejected. Changes are saved on submit. Average juror ratings are shown alongside each entry.'},
                ],
            },
            {
                'name': 'Promote Artworks',
                'where_used': 'Open call promotion page',
                'breadcrumb': 'Home > Shows > Select Show > Promote',
                'fields': [
                    {'name': '(confirm button)', 'input_type': 'form submit', 'purpose': 'Adds all Selected artworks and their artists to the show, sets the status to Published, and sends acceptance/rejection emails to every submitting artist — all in one step.'},
                ],
            },
            {
                'name': 'Event Form',
                'where_used': 'Event create/edit pages',
                'breadcrumb': 'Home > Events > New or Event Detail > Edit',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Event title.'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Public event description.'},
                    {'name': 'show', 'input_type': 'dropdown select', 'purpose': 'Show this event belongs to.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Event image shown on detail pages.'},
                    {'name': 'date', 'input_type': 'date input', 'purpose': 'Calendar date for the event.'},
                    {'name': 'start', 'input_type': 'time input', 'purpose': 'Event start time.'},
                    {'name': 'end', 'input_type': 'time input', 'purpose': 'Event end time.'},
                    {'name': 'tags', 'input_type': 'multi-select', 'purpose': 'Event tags used for filtering and curation.'},
                ],
            },
            {
                'name': 'Juror Assignment',
                'where_used': 'Show reviews page → Manage jurors',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Manage jurors',
                'fields': [
                    {'name': 'artist', 'input_type': 'dropdown select', 'purpose': 'Choose an artist with a linked user account to assign as juror for this show. Once assigned they can log in and score submitted artworks.'},
                ],
            },
            {
                'name': 'Rubric Criteria Form',
                'where_used': 'Show reviews → Manage rubric criteria',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Manage rubric criteria',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Criterion label shown to jurors when scoring, e.g. "Originality" or "Technical execution".'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Optional guidance to jurors explaining what to consider for this criterion.'},
                    {'name': 'weight', 'input_type': 'numeric input', 'purpose': 'Relative importance of this criterion. Higher weight contributes more to the composite score. For example, weights of 2, 1, 1 give the first criterion twice the influence.'},
                    {'name': 'order', 'input_type': 'numeric input', 'purpose': 'Display order shown to jurors. Lower numbers appear first. Use 0, 10, 20 etc. to leave room for reordering.'},
                    {'name': 'DELETE', 'input_type': 'checkbox', 'purpose': 'Check to remove this criterion. Deleting a criterion also removes all juror scores for it.'},
                ],
            },
            {
                'name': 'Curator Review Edit Form',
                'where_used': 'Artwork reviews detail (curator view)',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Select Artwork > Edit Review',
                'fields': [
                    {'name': 'rating', 'input_type': 'number input (0–100)', 'purpose': 'Adjust juror score when corrections are required.'},
                    {'name': 'body', 'input_type': 'multi-line text area', 'purpose': 'Adjust juror note text when needed.'},
                ],
            },
        ],
    },
    'juror': {
        'title': 'Juror Guide',
        'summary': 'Jurors review and score artworks for the specific shows they have been assigned to.',
        'allowed_actions': [
            'Access the Reviews page for shows you have been assigned to as juror.',
            'Use the Review Slideshow for fast, efficient scoring: image on the left, scoring buttons on the right, instant save with no Submit button.',
            'Score each submitted artwork using five levels: Weak, Developing, Solid, Strong, Exceptional (mapped to 10, 30, 50, 70, 90). If no rubric is defined, give an overall 0–100 rating.',
            'Use the "Skip weak" toggle in the slideshow to filter artworks with any Weak score out of your navigation flow — they get a red thumbnail and are skipped by arrow keys and auto-advance.',
            'Auto-advance moves to the next unscored artwork automatically once all criteria are scored.',
            'Press Enter or D in the slideshow to open the artwork detail page (blind if the show uses blind review). Press Back to return to the slideshow.',
            'Alternatively, score artworks individually from the Pending Review list on the Reviews page.',
            'You can return to update your scores at any time before the curator closes the review phase.',
            'Optionally add qualitative review notes alongside your scores.',
        ],
        'forms': [
            {
                'name': 'Review Slideshow',
                'where_used': 'Reviews page → Review Slideshow button',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Review Slideshow',
                'fields': [
                    {'name': 'Weak / Developing / Solid / Strong / Exceptional', 'input_type': 'click buttons per criterion', 'purpose': 'Score each rubric criterion. Saves instantly on click. Keyboard shortcut: 1–5.'},
                    {'name': 'Auto', 'input_type': 'checkbox (top bar)', 'purpose': 'When checked, the slideshow advances automatically to the next unscored artwork after all criteria are scored.'},
                    {'name': 'Skip weak', 'input_type': 'checkbox (top bar)', 'purpose': 'When checked, artworks with any Weak score are skipped by arrow navigation and auto-advance. They get a red thumbnail border.'},
                    {'name': 'Notes', 'input_type': 'text area (right panel)', 'purpose': 'Optional qualitative notes visible to the curator. Saved when you leave the field.'},
                    {'name': '↗ link / Enter / D key', 'input_type': 'navigation', 'purpose': 'Opens the artwork detail page. Respects blind review. Press Back to return to the slideshow.'},
                ],
            },
            {
                'name': 'Artwork Review Form (individual)',
                'where_used': 'Show review workflow — click Review on any artwork row',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Select Artwork',
                'fields': [
                    {'name': 'criterion scores', 'input_type': 'number input (0–100) per criterion', 'purpose': 'Score each rubric criterion if the curator has defined one.'},
                    {'name': 'rating', 'input_type': 'number input (0–100)', 'purpose': 'Overall score when no rubric is defined.'},
                    {'name': 'body', 'input_type': 'multi-line text area', 'purpose': 'Optional qualitative review notes visible to the curator.'},
                ],
            },
        ],
    },
    'staff': {
        'title': 'Staff Guide',
        'summary': 'Staff have full access across all shows, artists, artworks, and review workflows.',
        'allowed_actions': [
            'All curator capabilities across all shows and events.',
            'Create new shows (only staff can create; curators can edit assigned shows).',
            'Change show status to advance any show through its lifecycle from any show edit page.',
            'See all shows regardless of status.',
            'Assign artists as curators of shows via the Show Edit page — this grants them edit access and makes their artist profile publicly visible.',
            'Assign jurors to any show from the show\'s Reviews page.',
            'View and edit juror reviews across all shows.',
            'Link unlinked artist records to user accounts from /accounts/link-artists/.',
            'Edit and Delete links are shown only for records you can manage.',
        ],
        'forms': [
            {
                'name': 'Artwork Form (Staff Controls)',
                'where_used': 'Artwork create/edit pages',
                'breadcrumb': 'Me page > Artworks > New, or Artwork Detail > Edit',
                'fields': [
                    {'name': 'artists', 'input_type': 'multi-select', 'purpose': 'Associate one or more artists with the work.'},
                    {'name': 'shows', 'input_type': 'multi-select', 'purpose': 'Associate the artwork with one or more shows. Artwork becomes publicly visible once added to a show whose status is Published or Closed.'},
                    {'name': 'tags', 'input_type': 'multi-select', 'purpose': 'Internal or public categorization tags.'},
                ],
            },
            {
                'name': 'Link Artist to User',
                'where_used': 'Staff-only artist linking page',
                'breadcrumb': '/accounts/link-artists/',
                'fields': [
                    {'name': 'artist', 'input_type': 'dropdown select', 'purpose': 'Unlinked artist record to claim. Only artists with no user account are listed.'},
                    {'name': 'user', 'input_type': 'dropdown select', 'purpose': 'User account to associate with the selected artist record.'},
                ],
            },
            {
                'name': 'Show Form (Staff Fields)',
                'where_used': 'Show create/edit pages',
                'breadcrumb': 'Shows > New (top of page) or Show Detail > Edit',
                'fields': [
                    {'name': 'status', 'input_type': 'dropdown select', 'purpose': 'Controls the show lifecycle and public visibility. Only curators and staff can change this field.'},
                    {'name': 'curators', 'input_type': 'multi-select', 'purpose': 'Assign artists as curators. They gain edit access to the show and become publicly visible.'},
                    {'name': 'show_type', 'input_type': 'dropdown select', 'purpose': 'Gallery Show or Public Art Site. Affects the badge and display on show cards.'},
                    {'name': 'location', 'input_type': 'text area', 'purpose': 'Address or site description for public art installations.'},
                ],
            },
        ],
    },
}
