HOW_TO_GUIDES = [
    {
        'title': 'How to sign up for an account',
        'roles': None,
        'steps': [
            'Open the Account menu in the navigation and choose Sign Up.',
            'Enter your first name, last name, email address, and password — or use the "Continue with Google" option to skip the password. There is no separate username; your email address is how you log in.',
            'After signing up, an artist profile is automatically created for you using your name and email. If your email matches an existing artist record you were added under, the link is made for you automatically.',
            'If you were added under a different email, visit your artist edit page after signing in — you will see a link to claim your existing record. See "Linking your account to an existing artist profile" in the how-to guides for full details.',
        ],
    },
    {
        'title': 'How to complete your artist profile',
        'roles': {'artist', 'curator', 'juror', 'staff'},
        'steps': [
            'After signing up you are taken directly to your artist profile edit page — fill in your details there.',
            'If you need to return to your profile later, sign in — you will be taken to your Me page. Click Edit on your artist profile.',
            'Fill in your bio, statement, website, Instagram handle, Venmo, and upload a profile photo.',
            'The email on your artist record is your public contact address (used for invitations and curator communication). It can be different from your login email. Update it on the edit page if needed.',
            'Your profile becomes publicly visible once you are part of a show whose status is Published or Closed, or once a staff member adds you as a curator of a show.',
        ],
    },
    {
        'title': 'How to add artworks',
        'roles': {'artist', 'curator', 'juror', 'staff'},
        'steps': [
            'Sign in — you will be taken to your Me page. Find the Artworks section and click the New button.',
            'Fill in the title, year, medium, dimensions (width × height × depth), and upload an image — image is required for new artworks.',
            'Optionally set the pricing type (For Sale, Price on Request, Best Offer, or Not For Sale), add a price if applicable, set a replacement cost, and add a description.',
            'If the piece is framed and its outer size differs from the artwork dimensions, fill in the optional "Framed size" (width × height × depth) under Additional details. The layout editor and 3D view use the framed size when present (otherwise the artwork dimensions); placards still show the artwork dimensions. Leave blank for unframed work.',
            'Optionally record the "Hang drop" (under Additional details): the distance from the bottom edge of the piece up to its hanging point (wire pulled taut, or hook). Measure it once; the layout tool\'s Hang Info then shows the exact screw-hole height for wherever the piece is placed.',
            'Newly added artworks are private until they are included in a show whose status is Published or Closed.',
        ],
    },
    {
        'title': 'How to submit artwork to a show (open call or invitation-only)',
        'roles': {'artist', 'curator', 'juror', 'staff'},
        'steps': [
            'The submission steps are the same for open call and invitation-only shows. The only difference: for an invitation-only show you must first have been invited. You receive an invitation email with a personal accept link — open it (after signing in, or signing up with any email) to link the invitation to your account. If your account email already matches the invited address you are recognized automatically, no link needed.',
            'Sign in — you will be taken to your Me page. Find the show you want to submit to under "Shows Accepting Submissions" and click the Submit button. (Invitation-only shows appear there once you have been invited and the show is accepting submissions.)',
            'Select the one artwork card you want to submit (click it to highlight it), then click Submit. You submit one artwork at a time — repeat for each piece. Each artwork can only be submitted once per show.',
            'Some shows cap how many artworks each artist may submit. When a limit is set, the submit page shows your allowance (e.g. "up to 3 per artist — you can submit 2 more"); once you reach it, the page tells you and you cannot submit more.',
            'You will receive a confirmation email. Your submission appears on your Me page and on the show detail page as "Submitted".',
            'You can remove your submission while the show is still accepting submissions by clicking Retract next to your artwork on your Me page or the show detail page. Retracting permanently removes the submission — you can resubmit a different artwork while the show is still open.',
            'Once the show moves to In Review, submissions are closed and you cannot retract.',
            'You will receive an acceptance or rejection email when the curator publishes the show.',
        ],
    },
    {
        'title': 'How to create a show (staff only)',
        'roles': {'staff'},
        'steps': [
            'Sign in as a staff user, then go to Shows in the navigation.',
            'Click New at the top of the Shows page.',
            'Enter the show name, dates, description, and upload a hero image.',
            'Choose a Submission Type: "Open" for a public open call, or "Invited" for an invitation-only show.',
            'Set the Submission Deadline (required), Review Deadline (when jurors must finish scoring), and Decision Date (when artists will be notified — informational only).',
            'To assign a curator, add them in the Curators field — artists do not need a linked user account to be listed as curators.',
            'Optionally associate the show with a site by selecting it in the Sites field. This makes the show appear on the site detail page.',
            'New shows start with status "Under Consideration" — they are private and only visible to staff, curators, and jurors.',
            'Save the show. The curator can then edit the show and advance it through the lifecycle.',
        ],
    },
    {
        'title': 'Show lifecycle and status',
        'roles': {'curator', 'staff'},
        'steps': [
            'Every show has a status that controls who can see it and what actions are available.',
            'Change the status using the → button shown next to the current status on the show detail page (visible to curators and staff only).',
            'Under Consideration — private. Use this while planning. Only staff, curators, and jurors can see the show.',
            'Open Call — public. Invited artists (or everyone, for open shows) can submit work. Displays an "Open Call" or "Invitation Only" badge. Set this when you are ready to accept submissions.',
            'In Review — public (open shows only). Submissions are closed. Jurors score submitted artworks. Setting this status automatically emails all assigned jurors.',
            'Draft — private. Use this to assemble and curate the show privately before publishing. Entering Draft mode automatically adds all currently-selected artworks to the show so you can use the room layout tool.',
            'Published — public. The show is live. Setting this redirects to the Publish page where you confirm which artworks to include and sets the status to Published. Acceptance/rejection emails are NOT sent automatically — use the "Send Emails" button on the show detail page when you are ready to notify artists.',
            'Closed — public. The show has ended. It remains visible but indicates the run is complete.',
            'Staff and curators can always see shows in all statuses. Jurors can also see all shows regardless of status.',
        ],
    },
    {
        'title': 'How to run an invitation-only show',
        'roles': {'curator', 'staff'},
        'steps': [
            'Create the show (staff only) with Submission Type set to "Invited" and a submission deadline.',
            'On the show detail page, click "Invite Artists" to add artists by email address (one per line, or comma/semicolon separated). Saving only emails people who have not been emailed yet, so you can add more names later without re-inviting everyone.',
            'The Invite Artists page shows a progress table: whether each invited artist has created an account, completed their profile, how many artworks they have uploaded, how many they have submitted, whether the email was sent, and — in the Accepted column — whether they have claimed their invitation.',
            'Each row has controls to fix a wrong/typo\'d email in place, Resend the invitation, or Copy link to send the accept link directly (text, DM, another email) if the emailed invitation does not arrive.',
            'The invitation email contains a personal accept link. When the artist opens it — after signing in or signing up with ANY email — the invitation binds to their account, so a mismatched signup email no longer blocks them. If their account already uses the invited email, they are recognized automatically without needing the link.',
            'Change the show status to Open Call on the show detail page. Invited artists can now submit their work.',
            'To add work for an artist who cannot submit themselves (no account/email, or you manage them directly), open the Submissions page and click "Add artwork on behalf of an artist" — see the dedicated guide. This bypasses the invitation requirement.',
            'After the submission deadline, change the show status to Draft on the show detail page to close submissions.',
            'Go to the Submissions page. Use individual card dropdowns for one-at-a-time decisions, or use bulk select for many at once: click card backgrounds to select them, Shift+click for range select, drag on the grid background to rubber-band select, or click "☑ All" in a section heading. The action bar at the bottom moves all selected cards in one step. Alternatively, use the Curation Slideshow for a full-screen decision workflow.',
            'When your selections are final, change the show status to Published on the show detail page. This redirects to the Publish Show confirmation page.',
            'Review the diff and click "Confirm & Publish Show". This adds all Selected artworks to the show and sets the status to Published.',
            'Back on the show detail page, click "Send Emails" to notify artists of their acceptance or rejection. The emails are sent in the background — the page returns immediately. The button shows how many are pending and how many have already been sent, so it is safe to click again if something goes wrong without sending duplicates.',
            'Change the show status to Closed when the show run ends.',
            'Optionally add events (openings, talks) using the New Event link on the show detail page.',
        ],
    },
    {
        'title': 'How to add artwork on behalf of an artist (curator/staff)',
        'roles': {'curator', 'staff'},
        'steps': [
            'Use this when an artist cannot self-submit — for example a person you manage who has no email or account (such as an artist with a caregiver acting for them), or any artist you want to add to an invitation-only show directly. The artist needs no account, email, or submission of their own.',
            'If the artist does not exist yet, create their profile first (Artists → New): fill their name, first/last name, a profile photo and zip code (required to appear in shows), and leave "Linked user account" blank. The email field can be a caregiver\'s address or left blank — it is never sent to the artist.',
            'Go to the show\'s Submissions page and click "Add artwork on behalf of an artist".',
            'Choose the artist from the dropdown. The page then lists that artist\'s existing artworks.',
            'Either select one of their existing artworks and click "Add selected artwork to show", OR fill in the "Create a new artwork" form (title, medium, dimensions, image, price) and click "Create & add to show".',
            'The piece is added to the show as a curator-selected submission. On a Published show it appears immediately (in the layout editor and 3D view); on a show still in Draft/Open Call it is marked Selected and is added when you Publish/Promote, alongside the other selections.',
            'If that artist later gets their own account, a staff user can link the profile to it at /accounts/link-artists/ — nothing you added is lost.',
        ],
    },
    {
        'title': 'How to run an open call show',
        'roles': {'curator', 'staff'},
        'steps': [
            'A staff member creates the show with Submission Type set to "Open" and a submission deadline. As curator you can then edit the show name, dates, description, and hero image.',
            'Change the show status to Open Call on the show detail page. The show is now public and artists can submit work.',
            'Optionally define a rubric (weighted scoring criteria) from the Reviews page. Click "Manage Rubric Criteria" to add, edit, or remove criteria. If a previous show already has the rubric you want, use the "Copy rubric from another show" dropdown on that page to import it in one step — existing criteria are replaced.',
            'Optionally assign jurors now via Assign Jurors on the show detail page, or wait until after submissions close.',
            'Artists submit their work via the show detail page. You can monitor submissions at any time via Submissions on the show detail page.',
            'When the submission period ends, change the show status to In Review on the show detail page. Submissions are now closed and all assigned jurors are emailed automatically.',
            'Jurors score each submitted artwork. Monitor progress on the Reviews dashboard. Use the per-juror Slideshow buttons in the Juror Progress table to see each juror\'s scoring order.',
            'Change the show status to Draft on the show detail page. This closes the review phase and lets you work privately.',
            'Go to the Submissions page. Artwork cards are sorted by weighted score (highest first). For individual decisions, use the dropdown on each card — the page scrolls automatically to the next card after each change. For bulk decisions, click card backgrounds to select them (blue outline), use Shift+click for range select, or drag on the grid background to rubber-band select a region (hold Shift to add to the current selection). The "☑ All" button in each section heading selects the entire section. Once cards are selected, a bar appears at the bottom of the screen — click → Undecided, → Selected, or → Rejected to move them all at once. The total width of selected flat wall art is shown next to the Selected heading.',
            'Alternatively, use the Curation Slideshow on the Reviews page for a full-screen decision workflow with jury scores visible.',
            'When your selections are final, change the show status to Published on the show detail page. This redirects to the Publish Show confirmation page showing what will be added and removed.',
            'Review the diff and click "Confirm & Publish Show". This adds all Selected artworks to the show and sets the status to Published.',
            'Back on the show detail page, click "Send Emails" to notify artists of their acceptance or rejection. Emails are sent in the background so the page never times out, even for large shows. The button shows pending vs. sent counts and is safe to re-click — artists who already received an email will not be sent a duplicate.',
            'Change the show status to Closed on the show detail page when the show run ends.',
        ],
    },
    {
        'title': 'How to run a public art site open call',
        'roles': {'curator', 'staff'},
        'steps': [
            'A physical gallery location (called a "venue" in these docs, a "site" in the system) must exist before you create the show. If it does not exist yet, a staff member must create it first — see "How to create and manage sites" for those steps.',
            'Create the show (staff only). Set Show Type to "Public Art Site". In the Sites field, select the venue this show is associated with — the show will then appear on that venue\'s detail page.',
            'Optionally fill in the Location text field with any supplementary address or installation notes to display on the show detail page.',
            'Set Submission Type to "Open" (or "Invited") and set a submission deadline as you would for a regular open call.',
            'The show will display a "Public Art" badge on its card and detail page.',
            'All other open call steps (status transitions, submissions, jury, promote) work the same as a gallery open call.',
        ],
    },
    {
        'title': 'How to jury a show',
        'roles': {'juror', 'curator', 'staff'},
        'steps': [
            'Make sure you have an account on this site and that your artist profile information is complete — the curator will need to assign you by name.',
            'A curator or staff member assigns you as a juror. You will receive an email when the show moves to In Review status.',
            'Sign in and go to Shows. Open the show you are jurying and click Reviews on the show detail page.',
            'You will see a Pending Review section listing all artworks you have not yet scored. The fastest way to score is the Review Slideshow — see "How to use the Review Slideshow" for step-by-step instructions.',
            'Alternatively, click Review on any individual artwork to score it on its own page.',
            'If the curator has defined a rubric, score each criterion individually. Otherwise rate the artwork overall.',
            'Optionally add review notes. Scores save instantly in the slideshow, or click Submit review on the individual page.',
            'You can return to update your scores at any time before the curator closes the review phase.',
            'Your scores are averaged with other jurors\' scores and shown to the curator on the Reviews dashboard.',
            'If you are also a curator of this show, scroll past the curator overview section on the Reviews page to find your own Pending Review section.',
        ],
    },
    {
        'title': 'How to use the Review Slideshow',
        'roles': {'juror', 'curator', 'staff'},
        'steps': [
            'From the Reviews page for your show, click the "Review Slideshow" button next to the "Pending Review" heading. The slideshow opens full-screen.',
            'The artwork image fills the left side. The right side shows the artwork title, artists (hidden if the show uses blind review), and one scoring button row per rubric criterion.',
            'Click a score button — Weak, Developing, Solid, Strong, or Exceptional — to record your score for that criterion. Your score saves instantly; there is no Submit button.',
            'When all criteria are scored the slideshow automatically advances to the next unscored artwork (if Auto is checked in the top bar). Uncheck Auto to advance manually.',
            'Use the ← → arrow keys or the on-screen arrows to move between artworks at any time.',
            'Press 1–5 on the keyboard to score the focused criterion (highlighted in the left border). Press Tab to move focus to the next criterion.',
            'Thumbnail strip at the bottom: gold border = partially scored, green border = fully scored, teal outline = current artwork.',
            'Press Enter or D (or click the ↗ link in the top bar) to open the artwork detail page. If the show uses blind review the detail page opens without artist information.',
            'After viewing the artwork detail, press the browser Back button. The slideshow reopens at the artwork you were on.',
            'Press Esc or click × to close the slideshow at any time. Your scores are already saved.',
            'Press ? for a quick keyboard reference.',
        ],
    },
    {
        'title': 'How to use the Curation Slideshow',
        'roles': {'curator', 'staff'},
        'steps': [
            'From the Reviews page for your show, click the "Curation Slideshow" button next to the "Artworks" heading, or click a "Slideshow" button next to any individual decision section (Undecided, Selected, or Rejected) to start from that group.',
            'Artworks are presented in order from highest to lowest overall jury score, so the strongest candidates appear first.',
            'The artwork image fills the left side. The right side shows the artwork title, artists (hidden if the show uses blind review), year, medium, and dimensions.',
            'Below the artwork info the right panel shows the jury scores: each juror\'s name, their score on each rubric criterion, and their weighted total. The overall score averaged across all jurors is shown at the top in teal.',
            'Weak scores (the lowest rating) are shown in red so you can spot them at a glance.',
            'At the bottom of the right panel are three decision buttons: Undecided, Selected, and Rejected. Click one to record your decision. It saves instantly and the slideshow advances to the next artwork after a moment.',
            'The top bar shows a running count: Selected, Rejected, and Undecided.',
            'Thumbnail strip at the bottom: green border = selected, red border = rejected, gray border = undecided, teal outline = current artwork.',
            'Use the ← → arrow keys or on-screen arrows to navigate without recording a decision.',
            'Keyboard shortcuts: S = Selected, R = Rejected, U = Undecided, ← → = navigate, Enter or D = open detail page, Esc = close.',
            'Press Enter or D to open the artwork detail page. If the show uses blind review the detail page opens without artist information. Press the browser Back button to return to the slideshow at the same position.',
            'To see a single juror\'s scoring order, go to the Reviews dashboard and click the "Slideshow" button next to that juror\'s name in the Juror Progress table.',
            'When you are finished, close the slideshow with Esc or ×. Your decisions are already saved. To publish the show, go to the show detail page and follow the standard → Published / Confirm & Publish Show workflow.',
        ],
    },
    {
        'title': 'How to place artwork in the room layout editor',
        'roles': {'curator', 'staff'},
        'steps': [
            'From the show detail page, click "Layout" in the curatorial button row. This opens the room layout editor for the show\'s associated site.',
            'The editor shows a top-down floor plan with the room walls. Select a wall by clicking its tab at the top (N, E, S, W) — the selected wall is shown in the main canvas area.',
            'Toolbar layout: the Arrange buttons (Center, Distribute, Group/Ungroup, Rotate, Remove) appear only when you have pieces selected; the occasional view/measure tools (Fit, Measure, Hang Info, Ruler, ruler-zero toggle) live under the "View" menu; Undo, Save, Snapshots, and 3D View are always shown.',
            'To place an artwork, click it in the sidebar on the left (it appears centered on the wall), or drag it from the sidebar onto the wall to drop it exactly where you want. Then drag it to fine-tune its position.',
            'To adjust the height from the floor (measured to the center of the artwork), use the Height field in the position bar below the canvas after clicking an artwork.',
            'The position bar below the canvas shows the artwork\'s horizontal position (inches from the left edge of the wall), height to center (from floor), and the four edge distances: ← left, → right, ↑ top, ↓ bottom edges.',
            'To move a placed artwork, drag it directly on the canvas. Left/right dragging moves it along the wall; the position bar updates live.',
            'To delete a placed artwork, select it (click it) then press the Delete or Backspace key, or click the Remove button in the position bar.',
            'To find a placed artwork\'s wall and scroll the view to it, click its thumbnail in the sidebar — the editor switches to that wall and centers the view on the artwork.',
            'To distribute artworks evenly: select multiple artworks (click then Shift-click), then click Distribute H (horizontal) or Distribute V (vertical). The first and last artwork stay anchored; artworks in between are spaced with equal gaps.',
            'Corner handles appear at the edges of each wall. Include a corner in a selection to anchor your distribute operation against the wall edge.',
            'Obstacles (such as doors or windows set up in the site configuration) appear as grey rectangles. They are selectable for distribute operations — useful for placing artwork relative to a door opening.',
            'Use the scroll wheel or pinch gesture to zoom. Pan by clicking and dragging on empty canvas space, or use the W A S D keys. Click "Fit" in the toolbar (or press F) to reset the zoom/pan so the whole wall fits the view.',
            'Zoom is real-pixel: artwork images sharpen as you zoom in, and the position bar stays usable at all zoom levels.',
            'Click "Ruler" in the toolbar to show tick marks along the wall edges — long ticks every 10 inches, short ticks every inch. Horizontal is measured from the LEFT edge and vertical from the floor; big ticks are labelled with their distance in inches from zero. Use the "0: left / centre" button to switch the horizontal zero to the wall centre (handy for placing symmetric obstacles) — this also switches the position bar Horiz field (from left / from centre) to match. Tick lengths scale with zoom, and inch ticks/labels appear once you zoom in enough to read them.',
            'Rotate: select a piece (or a support, or a group) and click Rotate in the toolbar — it turns the selection 90° about the vertical axis. Group joins selected pieces so they move and rotate together; Ungroup separates them (and detaches a piece from a support).',
            'Supports (pedestals and shelves): a support is a plain box a piece can sit on — a pedestal on the floor/ceiling, a shelf on a wall. Clicking "＋ Add support" adds a new support to the tray in the sidebar (it is NOT placed yet); drag a tray chip (or a "Supports" catalog entry) onto the wall to place it where you drop it. Catalog entries come from the site\'s catalog (staff define them per site). Select a placed support to set its Name, size (W/H/D), height and texture in the support panel; the Name shows on its list row and is reused when you "Save to site catalog". The Texture dropdown offers the site catalog\'s textures plus "None (white)"; the default is white with a black outline.',
            'Put a piece on a support by dragging it over the support — they auto-group (shown by a green box) and the piece centres and rests on top. From then on they move together: moving the piece (drag, the Height/Horiz fields, or arrow keys) moves the support in lock-step, and moving the support carries its pieces. Use Ungroup to detach a piece so it can move on its own. Remove a selected support with the toolbar Remove button or the Delete key.',
            'Each piece shows a 5x3" placard label (name, artist, medium, dimensions, price) to its right (a flat card beside a pedestal on the floor). Placards follow their piece and appear in the 3D view too.',
            'When finished, the layout is saved automatically (about a second after your last change). The 3D View is read-only and never changes the layout; clicking "3D View" flushes any pending save first, and leaving the editor with unsaved changes shows a browser warning — so a round trip to 3D and back cannot lose or alter your layout.',
            'Snapshots (restore points): click "Snapshots" in the toolbar to save the current layout under a name, or roll back to an earlier one. See the dedicated "How to save and restore layout snapshots" guide. A snapshot of the current layout is also taken automatically before every save, so an accidental change (or an old browser tab overwriting your work) can always be undone.',
        ],
    },
    {
        'title': 'How to save and restore layout snapshots',
        'roles': {'curator', 'staff'},
        'steps': [
            'In the room layout editor toolbar, click "Snapshots" to open the snapshot panel.',
            'To save a restore point: type a name (e.g. "Opening night final") and click Save. This stores the current layout — room dimensions, supports, and every artwork placement.',
            'The list shows your saved (green "saved") snapshots and automatic (grey "auto") ones, each with when it was taken, who took it, and how many pieces/supports it holds. Automatic snapshots are captured before every save and every restore.',
            'To roll back: click "Restore" next to a snapshot and confirm. The current layout is replaced by that snapshot. The current state is auto-saved first, so a restore is itself undoable — if you restore the wrong one, restore the newest "auto" snapshot to get back.',
            'To remove ones you no longer need, click the trash (🗑) button on a snapshot row and confirm. Close the panel with the × button, the Escape key, or by clicking outside it.',
            'Why this exists: the layout is shared, and saving replaces the whole layout. If two people (or two browser tabs/devices) edit the same show, the last save wins — an old tab can overwrite newer work. Snapshots let you recover. Best practice: save a named snapshot before big changes, and avoid leaving stale layout tabs open on other devices.',
            'Stale-edit guard: if the layout was changed elsewhere since you opened the editor, your next save is caught instead of silently overwriting — you are asked to either reload the latest version (recommended) or overwrite it with what is on your screen. If you ever see "Save failed" repeatedly right after a deploy, the database may be missing a migration; a site admin should run "python manage.py migrate".',
            'Advanced (staff, command line): "python manage.py export_layout <show-slug> --out file.json" saves a layout to a file, and "python manage.py import_layout <show-slug> file.json" restores it — useful for off-site backups or moving a layout between environments.',
        ],
    },
    {
        'title': 'How to print placards for a show (Avery 5376 cards)',
        'roles': {'curator', 'staff'},
        'steps': [
            'On the show detail page, click "Placards PDF" (visible to curators/staff). This downloads a PDF with one placard per artwork in the show.',
            'The PDF is laid out for Avery 5376 business-card sheets — US Letter, ten 2 × 3.5 inch cards per page (2 columns × 5 rows). The same layout also fits Avery 5371, 8371, and 8471.',
            'Each card shows the title, year(s), artist(s), medium, and dimensions — no price — plus a QR code on the right that links to the artwork\'s page (so visitors can scan it to see more or inquire). Long titles and mediums wrap to two lines; the whole block then shrinks to fit beside the QR, and anything that still won\'t fit is trimmed with an ellipsis rather than spilling off the card. Accented and non-Latin characters (e.g. é, ñ, ü, Cyrillic/Greek) render correctly. Add ?qr=0 to the link if you want text-only cards without the QR.',
            'Cards are ordered by the show artwork number (then title). Load Avery 5376 stock in your printer and print at 100% / "Actual size" (do NOT use "fit to page", which would shift the alignment).',
            'To check alignment on plain paper first, add ?outlines=1 to the PDF link (e.g. …/placard-sheet/?outlines=1) to draw faint card borders; print it, hold it against a blank Avery sheet to confirm registration, then print the real one without outlines.',
        ],
    },
    {
        'title': 'How to download a show checklist PDF',
        'roles': {'curator', 'staff'},
        'steps': [
            'On the show detail page, click "Checklist PDF" (visible to curators/staff). This downloads a print-ready exhibition checklist for the whole show.',
            'It opens with a cover page: the show title, "Curated by…", the date range, any opening/events, the list of participating artists (in as many columns as needed for the count), and the show image with the description flowing around it. HTML in the description is stripped to clean text.',
            'Then one entry per artwork — a small thumbnail with the artist, title (year), medium, dimensions, and price (with "Not For Sale" / "Price on Request" handled) — grouped by artist.',
            'It ends with an "Artists" section — every participating artist\'s photo with their name (Instagram right after it), then their bio and their Statement (the statement is labelled "Statement:"), flowing around the photo — then the curator(s). Everyone is listed with their name and photo even if they have no bio/statement; HTML in bios/statements is stripped.',
            'Every page footer shows the site\'s logo and info (website, Instagram, and street address), pulled from the show\'s associated site. Empty fields are omitted, so fill in the site and artist profiles for the fullest checklist.',
            'This is separate from the Avery placard sheets and prints on plain US-Letter paper.',
        ],
    },
    {
        'title': 'How to view a show in 3D',
        'roles': {'curator', 'staff'},
        'steps': [
            'From the show detail page, click "3D View". This button is only visible when at least one artwork has been placed in the room layout (or you are a curator or staff member).',
            'The 3D viewer opens in the same browser tab. Click the browser Back button to return to the show detail page.',
            'On desktop, click once to enter look mode (pointer lock), then move the mouse to look around. Move through the space with W A S D or the arrow keys; Q and E turn; R resets. On touch, drag to look and use the on-screen buttons to walk. The camera starts at roughly eye level (5 feet from the floor).',
            'Setting the default start view: curators and staff see a "Set as start view" button in the top-left of the 3D viewer. Walk/look to the viewpoint you want visitors to open on, then click it (on desktop, press Esc first to leave look mode so the button is clickable). This saves the viewpoint on the site’s room configuration, so every visitor to any show at that site opens on this view by default. Pressing R still resets to the room centre; the saved view only sets where a fresh visit begins.',
            'Artworks appear on the walls where they were placed in the layout editor. Each piece shows its placard label beside it, and supports (pedestals/shelves) appear as boxes. Wall textures (if configured for the site) are applied to floor, ceiling, and each wall.',
            'When the crosshair is over a piece or its placard it lights up. Click a piece to open its artwork detail page — the browser Back button returns you to the exact spot you were standing (and closing an enlarged placard drops you straight back into navigation). Click a placard to enlarge it full-screen; press Return/Escape or click to dismiss.',
            'Obstacles (doors, windows) appear as semi-transparent grey rectangles at their configured positions.',
            'The viewer is performance-optimised for large rooms: image resolution is capped and lighting is simplified, so it should remain responsive on most devices.',
            'If artworks appear white or invisible, ensure the site\'s S3 bucket has a CORS policy allowing the site domain — see your administrator.',
        ],
    },
    {
        'title': 'How to set up install / drop-off and pickup times (curator)',
        'roles': {'curator', 'staff'},
        'steps': [
            'Decide who installs the work: on the show\'s Edit page, the "Artists install their own work" setting controls this. When ON (the default), artists schedule an INSTALL time (which is also when they bring the work — there is no separate drop-off). When OFF, the curator installs and artists schedule a DROP-OFF time instead.',
            'From the show detail page, click "Schedule Windows" in the curatorial button row.',
            'Under the first section (labelled "Install windows" or "Drop-off windows" depending on the setting above), add each date/time range when artists may come: pick a date, a start time, and an end time, then click Add. Add as many ranges as you need.',
            'Under "Pickup windows", do the same for the ranges when artists may collect their work after the show closes.',
            'To remove a window, click "remove" next to it. Any artist who had chosen a time in that window will need to pick a new one.',
            'Artists with accepted work see a "Schedule My Install & Pickup" (or "Drop-off & Pickup") button on the show page once at least one window exists; they choose a specific time within your ranges.',
            'To track arrivals, click "Schedule Tracker" on the show detail page. It lists every accepted artist with their chosen times (or "not scheduled").',
            'Tick the Done box in each column when an artist has installed/dropped off and when they have picked up. The summary at the top shows how many are done and how many are outstanding, so you know who to follow up with.',
        ],
    },
    {
        'title': 'How to schedule your art install / drop-off and pickup',
        'roles': None,
        'steps': [
            'After your work is accepted into a show and the curator has set up windows, open the show detail page and click "Schedule My Install & Pickup" (it may say "Drop-off & Pickup" if the curator installs the work).',
            'For the first event (Install or Drop-off), choose one of the available windows from the dropdown, enter a specific time within that window\'s range, and click Set.',
            'For Pickup (used after the show closes), do the same to choose when you will collect your work.',
            'If the show is self-install, your install time is also your drop-off — you bring and hang your work in one visit. If the curator installs, you only drop the work off at your chosen time.',
            'Your chosen times are shown on the page, and you can come back to update them any time before the window. The curator checks you off once your work arrives.',
            'After you set a time, "Add to calendar" links appear next to it: Google opens Google Calendar pre-filled; the Apple / Outlook (.ics) link downloads a calendar file that opens in Apple Calendar, Outlook, or any calendar app. Both include the gallery address.',
        ],
    },
    {
        'title': 'How to configure a site\'s room and walls (staff only)',
        'roles': {'staff'},
        'steps': [
            'Open the site detail page and click Edit, then scroll to the Room Configuration section.',
            'Enter the room dimensions: width, depth, and height (all in inches).',
            'Optionally upload texture images for each surface: North wall, East wall, South wall, West wall, floor, and ceiling. Leave any field blank to use a plain white surface.',
            'Scroll to the Walls & Obstacles section. Each wall (N, E, S, W) can have one or more obstacles such as doors or windows.',
            'For each obstacle, enter a label (e.g. "Front door"), select the wall it is on, and enter its position and dimensions (all in inches). Horizontal position is measured from the left edge of the wall; vertical position is measured from the floor.',
            'Obstacles appear as grey rectangles in the layout editor and as semi-transparent panels in the 3D viewer. Users can include them in distribute operations when placing artworks.',
            'Corner handles are always present at the edges of each wall and do not need to be configured.',
            'Under "Supports (catalog)" you define reusable pedestals/shelves (name, W/H/D, optional texture) that curators drag into a show\'s layout. The blank row at the bottom (placeholder "＋ New support") is for adding one — type a name and sizes, then Save. To remove a support, tick its Delete box and Save; to edit one, change its fields and Save.',
            'Save the site. Room configuration changes take effect immediately in the layout editor and 3D viewer.',
        ],
    },
    {
        'title': 'Linking your account to an existing artist profile',
        'roles': None,
        'steps': [
            'There are three cases — figure out which one applies, then follow the matching steps.',
            'Case 1 — Same email: You were already in the system and you signed up using the same email address that is on your artist record. The system linked your account automatically. No extra steps needed — just fill in your profile.',
            'Case 2 — Different email: You were already in the system but you signed up with a different email than the one on your existing artist record. Sign in, then go to your artist edit page — you will see a link to "link it to your account here". Click it, enter the OLD email address that is on your existing record, and submit. Your blank auto-created profile is replaced with your existing record, preserving all artworks and show history. The artist email is left unchanged (it is your public contact address and may intentionally differ from your login email — you can update it from the edit page if needed).',
            'Case 3 — New to the system: You have no existing record. A new artist profile was created for you automatically when you signed up. Go to your artist profile and fill in your bio, statement, website, Instagram, and upload a profile photo.',
            'Not sure which case applies? Email info@120710.art — a staff member can look up your record, tell you which email is on it, and link it for you if needed.',
        ],
    },
    {
        'title': 'How to submit artwork to a show, open call or invitation-only (new to the site)',
        'roles': None,
        'public_only': True,
        'steps': [
            'This works the same for open call and invitation-only shows. For an invitation-only show, first open the accept link in your invitation email — you can sign up with any email and it will link the invitation to your new account.',
            'Step 1 — Create an account: open the Account menu in the navigation and choose Sign Up. Enter your name, email, and password (or continue with Google).',
            'Step 2 — Complete your artist profile: after signing up you land on your artist profile edit page. Fill in your first name, last name, and zip code. Then upload a profile photo — this must be a photo of YOU (the artist), not a photo of your artwork. Your profile photo appears on your public artist page.',
            'Step 3 — Add your artwork: scroll down to the Artworks section on your Me page and click New. Fill in the title, year, medium, and dimensions, and upload an image of the artwork itself. Save.',
            'Step 4 — Submit: go to the show detail page. You will see a Submit button under "Shows Accepting Submissions" on your Me page, or directly on the show page. Click it, select the artwork card you just added, and click Submit.',
            'You will receive a confirmation email. Your submission appears on your Me page and on the show detail page.',
            'To remove a submission, click Retract next to your artwork. This permanently deletes that submission — you can resubmit a different artwork while the show is still open.',
        ],
    },
    {
        'title': 'How to pin artworks',
        'roles': None,
        'steps': [
            'Sign in. Browse any show or the Artworks gallery.',
            'On any artwork card, click the 📌 Pin button in the card footer. The button turns orange and shows "Pinned" to confirm it has been saved.',
            'You can also pin or unpin from within a slideshow — a 📌 button appears in the top bar next to the open-detail link.',
            'Pinned artworks appear on your artist profile page under "Pinned". The section is only visible to you.',
            'To arrange your pinboard, drag and drop the cards into any order — the order saves automatically.',
            'To unpin, click the orange 📌 Pinned button again on the card or artwork detail page.',
        ],
    },
    {
        'title': 'How to browse sites and use the site map',
        'roles': None,
        'steps': [
            'Click Sites in the navigation bar to open the Sites list page.',
            'At the top of the page a map shows every site that has coordinates set. Each site appears as a blue pin marker.',
            'Click any marker to open a small popup showing the site name. Click the site name link in the popup to go directly to that site\'s page.',
            'Pan the map by clicking and dragging. Zoom in and out using the + / − buttons in the top-left corner, the scroll wheel on a mouse, or a pinch gesture on a touchscreen.',
            'Below the map, site cards list all published locations with their name, city, and a View link. Click either the card image or the View link to open the site detail page.',
            'On a site detail page you can browse the shows, artists, and artworks associated with that location. Navigation links such as shows, artists, and artworks maintain the site context — the site name and icon stay in the navbar, and links go to site-scoped URLs rather than the global listing.',
            'To leave the site context and return to the global view, click the × button next to the site name in the navbar, or choose a top-level section from the main navigation.',
        ],
    },
    {
        'title': 'How to create and manage sites (staff only)',
        'roles': {'staff'},
        'steps': [
            'Sign in as a staff user, then click Sites in the navigation.',
            'Click New Site to open the site creation form.',
            'Enter the site name, address fields (street, city, state, postal code, country), description, contact details, and optionally a hero image and an icon (small logo shown in the nav bar and site cards).',
            'To set the map coordinates automatically, fill in at least the street address or city, then click "Look up coordinates from address". The latitude and longitude fields are filled from the OpenStreetMap geocoder — review the matched address shown beneath the button before saving.',
            'If geocoding fails or returns the wrong location, enter the latitude and longitude values manually.',
            'Set Status to Published to make the site visible to all visitors. Sites with Draft status are only visible to staff.',
            'In the Room Configuration section, enter the room dimensions (width, depth, height in inches) and optionally upload texture images for each wall surface (N/E/S/W), floor, and ceiling.',
            'In the Walls & Obstacles section, add obstacles such as doors or windows for any wall. Each obstacle needs a label, wall selection, position from the left edge, height from the floor, and dimensions.',
            'Save the site. It now appears in the Sites list and as a pin on the map (if coordinates are set). The room configuration is used by the layout editor and 3D viewer.',
            'To edit an existing site, open the site detail page and click Edit.',
            'To delete a site, open the site detail page, click Edit, then click Delete and confirm.',
        ],
    },
    {
        'title': 'How to record artwork ownership',
        'roles': None,
        'steps': [
            'Sign in. Navigate to the artwork detail page for a piece you own — purchased, received as a gift, or otherwise acquired.',
            'Click "Claim" in the button bar at the bottom of the artwork card. You cannot claim your own artwork — the Claim button is hidden for artworks you created.',
            'The artwork\'s artist sees your claim under "Pending Collection Confirmations" on their profile page and clicks Confirm or Decline. Curators and staff can also confirm or remove claims.',
            'While pending, a yellow "awaiting artist confirmation" badge appears on the artwork detail page.',
            'Once confirmed, a green badge appears and the piece is listed in your Collection on your public artist profile.',
            'From your profile, drag and drop collection cards to arrange them in any order — the order saves automatically.',
            'To remove a piece from your collection at any time, click "Unclaim" in the button bar on the artwork detail page.',
        ],
    },
    {
        'title': 'How to buy a piece of artwork',
        'roles': None,
        'steps': [
            'Find the artwork you are interested in — browse Shows or Artists from the navigation, or ask the gallery for a direct link.',
            'On the artwork detail page, check the price listed. If it shows "Not For Sale" the work is unavailable. If it shows "Price on Request" or "Best Offer", the artist will discuss pricing with you directly.',
            'Click the Inquire button on the artwork page. No account is required to inquire.',
            'Fill in your name, email address, and a message to the artist — for example, express your interest and ask any questions about the work. You may be asked to complete a quick "I\'m not a robot" verification.',
            'Submit the form. Your message is sent directly to the artist with your email address included so they can reply to you.',
            'The artist will follow up with you by email to arrange payment and delivery or pickup.',
            'Optional — record the piece in your own collection: once you own it you can display it in a personal Collection on this site. This is free and you do not need to be an artist.',
            'Create an account (see "How to sign up for an account"), then set up your profile (see "How to complete your artist profile") — your Collection is shown on your profile page.',
            'Go back to the artwork detail page and click "Claim" in the button bar. The piece\'s artist (or staff) confirms your claim, and it then appears in your Collection, where you can drag cards to reorder them. See "How to record artwork ownership" for the full claim/confirm flow.',
        ],
    },
    {
        'title': 'How to adjust card sizes',
        'roles': None,
        'steps': [
            'On any page that shows a card grid (artists, artworks, shows, submissions, etc.) a ▦ icon appears in the bottom-right corner of the browser window.',
            'Drag the slider next to the ▦ icon left to make cards smaller, right to make them larger. The percentage label updates live.',
            'The size range is 25% (very small thumbnails) to 200% (large cards). Your choice is saved in the browser and restored the next time you visit.',
            'Double-click the ▦ icon to reset the cards to the default 100% size.',
        ],
    },
    {
        'title': 'How to link an artist profile to a user (staff only)',
        'roles': {'staff'},
        'steps': [
            'Sign in as a staff user, then go to /accounts/link-artists/.',
            'Select the unlinked artist record from the first dropdown (only artists with no user account appear).',
            'Select the user account to link it to from the second dropdown.',
            'Click Link. The artist record is immediately associated with that user account.',
            'After linking, the user can sign in and manage that artist profile.',
        ],
    },
]

GENERAL_GUIDE = {
    'title': 'Account Basics',
    'summary': 'Use these steps to access your account and keep your profile current.',
    'allowed_actions': [
        'Sign in via Account → Log In in the navigation.',
        'Reset your password from the login page if you have forgotten it.',
        'Change your password via Account → Change Password in the navigation.',
        'Edit and Delete links only appear when your account can manage that record.',
        'Card grids on any page can be resized using the ▦ slider in the bottom-right corner. Your preferred size is saved between visits.',
    ],
    'forms': [
        {
            'name': 'Name Profile Form',
            'where_used': 'Account → Profile (/accounts/profile/)',
            'breadcrumb': 'Home > Account > Profile',
            'fields': [
                {
                    'name': 'first_name',
                    'input_type': 'text input',
                    'purpose': 'Your public first name shown throughout the site.',
                },
                {
                    'name': 'last_name',
                    'input_type': 'text input',
                    'purpose': 'Your public last name shown throughout the site.',
                },
            ],
        },
    ],
}


ROLE_DOCUMENTATION = {
    'artist': {
        'title': 'Artist Guide',
        'summary': 'Artists manage their own profile and artworks, and can submit work to open call and invitation-only shows.',
        'allowed_actions': [
            'Create and edit your artist profile.',
            'Create and edit your own artworks.',
            'Submit artworks to open call shows (or invitation-only shows where you have been invited) via the "Shows Accepting Submissions" section on your Me page.',
            'Track your submission statuses and retract submissions from the show detail page while the deadline is open.',
            'Once accepted into a show, schedule your install (or drop-off, if the curator installs) and your pickup by picking a specific time within the curator\'s available windows — use the "Schedule My Install & Pickup" button on the show page. On self-install shows, your install time is also when you bring the work.',
            'Your artworks and profile become publicly visible once you are part of a show whose status is Published or Closed.',
            'If you have an existing artist record that was created before you had an account, check your artist edit page after signing in — a notice will appear if your profile is empty, with a link to claim your existing record by entering the old email.',
            'If you are unsure which email is on your existing record, email info@120710.art and a staff member can look it up or link it for you.',
            'You cannot claim your own artworks as a collector — the Claim button is hidden for artworks you own.',
        ],
        'forms': [
            {
                'name': 'Artist Form',
                'where_used': 'Artist create/edit pages',
                'breadcrumb': 'Me page > Edit, or Artists list > Edit',
                'fields': [
                    {'name': 'first_name', 'input_type': 'text input', 'purpose': 'Given name for your artist profile.'},
                    {'name': 'last_name', 'input_type': 'text input', 'purpose': 'Family name for your artist profile.'},
                    {'name': 'email', 'input_type': 'email input', 'purpose': 'Contact email for curator/admin communication.'},
                    {'name': 'phone', 'input_type': 'text input', 'purpose': 'Optional contact phone number.'},
                    {'name': 'website', 'input_type': 'url/text input', 'purpose': 'External portfolio or personal website URL.'},
                    {'name': 'instagram', 'input_type': 'text input', 'purpose': 'Instagram handle starting with @.'},
                    {'name': 'venmo', 'input_type': 'text input', 'purpose': 'Venmo username starting with @.'},
                    {'name': 'bio', 'input_type': 'multi-line text area', 'purpose': 'Artist biography shown publicly.'},
                    {'name': 'statement', 'input_type': 'multi-line text area', 'purpose': 'Artist statement shown publicly.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Profile photo shown on artist pages.'},
                ],
            },
            {
                'name': 'Artwork Form',
                'where_used': 'Artwork create/edit pages',
                'breadcrumb': 'Me page > Artworks > New, or Artwork Detail > Edit',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Title of the artwork.'},
                    {'name': 'end_year', 'input_type': 'numeric input', 'purpose': 'Year the work was completed (or ending year for multi-year works).'},
                    {'name': 'start_year', 'input_type': 'numeric input', 'purpose': 'Starting year for multi-year works. Leave blank for single-year works.'},
                    {'name': 'medium', 'input_type': 'text input', 'purpose': 'Primary materials or medium.'},
                    {'name': 'width × height × depth', 'input_type': 'numeric inputs', 'purpose': 'Physical dimensions in inches. Depth is optional — omit for flat wall pieces, enter for 3-D works.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Primary artwork image. Required when creating a new artwork.'},
    {'name': 'layout_image', 'input_type': 'file upload', 'purpose': 'Optional cropped image of just the artwork, used only in the room layout editor and 3D viewer. Upload your own, or use the "Crop layout / 3D image from main image" button on the edit page to crop it in-browser (crop freely to the actual artwork — the corners drag independently). Defaults to the main image if left blank; not shown in cards.'},
                    {'name': 'pricing_type', 'input_type': 'dropdown select', 'purpose': 'Pricing type: For Sale (requires a price), Price on Request, Best Offer (optionally set a minimum), or Not For Sale.'},
                    {'name': 'price', 'input_type': 'numeric input', 'purpose': 'Required for For Sale; optional minimum for Best Offer. Hidden for Price on Request and Not For Sale.'},
                    {'name': 'replacement_cost', 'input_type': 'numeric input', 'purpose': 'Insurance or replacement value.'},
                    {'name': 'is_sold', 'input_type': 'checkbox', 'purpose': 'Marks the work as sold.'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Public description of the work.'},
                    {'name': 'installation', 'input_type': 'multi-line text area', 'purpose': 'Display or installation notes for the venue.'},
                ],
            },
            {
                'name': 'Open Call Submission Form',
                'where_used': 'Show detail page when the show is accepting submissions',
                'breadcrumb': 'Home > Shows > Select Show > Submit Artwork',
                'fields': [
                    {'name': 'artwork', 'input_type': 'artwork card grid (pick one)', 'purpose': 'Click the one artwork card you want to submit, then Submit — one artwork at a time. Each artwork can only be submitted once per show, and the show may cap the number of submissions per artist (shown on the page when a limit is set).'},
                ],
            },
        ],
    },
    'curator': {
        'title': 'Curator Guide',
        'summary': 'Curators manage shows and events, control show lifecycle status, run open call and invitation-only workflows, assign jurors, review aggregated jury ratings, and place artwork in the virtual room.',
        'allowed_actions': [
            'Edit and manage shows and events you are listed as curator for.',
            'See all shows regardless of status (Under Consideration, Draft, and other private statuses are visible to curators).',
            'See all artworks and artists including those not yet in any show.',
            'Advance a show through its lifecycle by clicking the → button next to the current status on the show detail page.',
            'Run open call shows: set status to Open Call to accept submissions, advance to In Review after the deadline, then select or reject submissions, promote selected artworks, and publish.',
            'Run invitation-only shows: invite artists by email, set status to Open Call so invited artists can submit, then advance to Draft, select or reject, and publish.',
            'Optionally cap how many artworks each artist may submit with "Max submissions per artist" on the show Edit page (blank = no limit). Artists submit one artwork at a time; the cap is enforced on submit.',
            'On the Invite Artists page you can fix a wrong invitation email in place, resend an invitation, or Copy link to send the accept link directly (it works with whatever account the artist signs in with); the Accepted column shows who has claimed their invitation. Re-saving the email list only emails people who have not been emailed yet.',
            'Monitor invited artists\' progress (account created, profile complete, artwork count, submission count) from the Invite Artists page.',
            'Define a weighted rubric for jury scoring: add named criteria with weights from the Manage Rubric Criteria page. Jurors score each criterion; the dashboard shows a weighted composite score per artwork.',
            'Assign artists as jurors for your show from the Reviews page. Jurors do not need special accounts — any artist with a linked user account can be a juror.',
            'View all juror reviews and weighted composite scores per artwork on the Reviews dashboard.',
            'Use the per-juror Slideshow buttons in the Juror Progress table to see each juror\'s scoring order as a full-screen slideshow.',
            'Use the Curation Slideshow to sort submissions into Selected, Rejected, or Undecided. Artworks are shown highest-score first. Scores and per-juror breakdowns are shown on the right. Decisions save instantly.',
            'On the Submissions page, artwork cards are sorted by weighted score (highest first). Use individual dropdowns for one-at-a-time changes, or bulk-select cards (click, Shift+click, or rubber-band drag) and move them all at once using the action bar that appears at the bottom of the screen.',
            'The total width of selected flat wall artworks (depth = 0) is shown next to the Selected heading on the Submissions page — useful for gauging how much linear wall space the selection requires.',
            'Place artwork in the virtual room using the Layout editor. Access it from the curatorial button row on the show detail page.',
            'View the placed artwork in 3D using the 3D View button on the show detail page. The button is hidden from the public until at least one artwork has been placed.',
            'Remove an artwork from a show (e.g. the artist withdrew it) with the "Remove from show" button on that artwork\'s card on the show detail page. This only pulls it from the show — the artwork and artist records are kept — and also clears any wall placement for it.',
            'Choose who installs the work with the "Artists install their own work" setting on the show Edit page: on (default) means artists schedule an install time that also serves as their drop-off; off means artists schedule a drop-off and you install. Set up the install/drop-off and pickup windows from "Schedule Windows", then use "Schedule Tracker" to check off which artists have installed/dropped off and collected their work, and see who is still outstanding.',
            'Edit juror reviews when corrections are needed.',
            'Your artist profile becomes publicly visible when you are added as a curator of a show.',
            'Edit and Delete links appear only for shows and events you are assigned to curate.',
        ],
        'forms': [
            {
                'name': 'Show Form',
                'where_used': 'Show edit pages (curators can edit, staff can create)',
                'breadcrumb': 'Shows > New (staff only) or Show Detail > Edit',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Show title shown in listings and detail pages.'},
                    {'name': 'show_type', 'input_type': 'dropdown select', 'purpose': 'Gallery Show or Public Art Site. Affects the badge shown on the show card.'},
                    {'name': 'location', 'input_type': 'text area', 'purpose': 'Address or supplementary installation notes. Shown on the show detail page for public art shows.'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Public show description.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Hero image for the show.'},
                    {'name': 'status', 'input_type': 'dropdown select', 'purpose': 'Controls the show lifecycle phase and visibility. Under Consideration and Draft are private (staff, curators, jurors only). Open Call, In Review, Published, and Closed are publicly visible. Only curators and staff can change this field.'},
                    {'name': 'blind_review', 'input_type': 'checkbox', 'purpose': 'When checked, artist names are hidden from jurors during review and from slideshow detail views. Useful for impartial jurying.'},
                    {'name': 'submission_type', 'input_type': 'dropdown select', 'purpose': 'Open — any artist can submit when the show is in Open Call status. Invited — only artists who have received an invitation email can submit.'},
                    {'name': 'max_submissions_per_artist', 'input_type': 'number input', 'purpose': 'Optional cap on how many artworks each artist may submit to this show. Leave blank for no limit. Enforced when artists submit (they submit one artwork at a time).'},
                    {'name': 'submission_deadline', 'input_type': 'date input', 'purpose': 'Required. Cutoff date for artist submissions. After this date, manually advance the status to Draft to close submissions.'},
                    {'name': 'review_deadline', 'input_type': 'date input', 'purpose': 'Target date for jurors to finish scoring. Shown to jurors so they know when their reviews are due (informational — does not lock automatically).'},
                    {'name': 'decision_date', 'input_type': 'date input', 'purpose': 'Target date for notifying artists of acceptance/rejection decisions (informational only — does not lock anything automatically).'},
                    {'name': 'start', 'input_type': 'date input', 'purpose': 'Show opening date. Artworks and artists become publicly visible from this date.'},
                    {'name': 'end', 'input_type': 'date input', 'purpose': 'Show closing date.'},
                    {'name': 'tags', 'input_type': 'multi-select', 'purpose': 'Categorization tags for filtering and organization.'},
                    {'name': 'curators', 'input_type': 'multi-select', 'purpose': 'Artists assigned as curators. All artists appear in this list, including those without linked user accounts, so historical curator credits are preserved.'},
                    {'name': 'sites', 'input_type': 'multi-select', 'purpose': 'Sites this show is associated with. The show appears on each selected site\'s detail page.'},
                ],
            },
            {
                'name': 'Room Layout Editor',
                'where_used': 'Show detail page → Layout (curatorial button row)',
                'breadcrumb': 'Home > Shows > Select Show > Layout',
                'fields': [
                    {'name': 'Wall tabs (N / E / S / W)', 'input_type': 'click to select', 'purpose': 'Switch which wall you are editing. Placed artworks on other walls remain in place.'},
                    {'name': 'Artwork sidebar', 'input_type': 'click or drag', 'purpose': 'Click an artwork thumbnail to place it on the current wall centered, or drag it onto the wall to drop it at that spot. Click a placed artwork\'s thumbnail to jump to its wall and highlight it.'},
                    {'name': 'Canvas drag', 'input_type': 'drag placed artwork', 'purpose': 'Move artwork along the wall. Position is shown live in the bar below the canvas. A piece sitting on a support drags the support (and any siblings) with it.'},
                    {'name': 'Position bar (below canvas)', 'input_type': 'numeric inputs', 'purpose': 'Edit the exact horizontal position (from left edge) and height (center from floor) in inches. Updates live as you drag. If the piece is on a support, the support moves with it.'},
                    {'name': 'Hang info overlay', 'input_type': 'read-only display', 'purpose': 'Shows the artwork dimensions, the four edge distances (← left, → right, ↑ top, ↓ bottom in inches), and ⊕ the horizontal centre distance from the left wall edge (where to drill the centre hole). If the artwork has a "Hang drop" recorded (bottom edge → hanging point), the vertical line also shows 🔩↑ the screw-hole height above the floor (bottom-above-floor + hang drop); combined with ⊕ on the horizontal line that gives the exact drill point. Text auto-fits inside the artwork card at any zoom level.'},
                    {'name': 'Placard', 'input_type': 'read-only display', 'purpose': 'A 5x3" wall label (name, artist, medium, dimensions, price) shown to the right of each piece; it follows the piece and appears in the 3D view.'},
                    {'name': 'Rotate button', 'input_type': 'button', 'purpose': 'Turns the selection 90° about the vertical axis — a piece, a support, or an art+support group.'},
                    {'name': 'Group / Ungroup buttons', 'input_type': 'button', 'purpose': 'Group joins selected pieces so they move and rotate together. Ungroup separates them, and detaches a piece from its support so it can move on its own.'},
                    {'name': 'Remove button / Delete / Backspace key', 'input_type': 'button or keyboard', 'purpose': 'Removes the selected artwork(s) — returned to the sidebar pool — or a selected support from the wall.'},
                    {'name': 'Supports tray / + Add support', 'input_type': 'click or drag', 'purpose': '"＋ Add support" adds a new support to the tray in the sidebar (not placed yet). Drag a tray chip — or a site catalog entry — onto the wall to place it where you drop it (a pedestal on the floor, a shelf on a wall). The × on a tray chip discards an unplaced support. Drop a piece onto a support to auto-group them.'},
                    {'name': 'Support panel (Name / size / Texture)', 'input_type': 'text, number, dropdown', 'purpose': 'With a support selected, set its Name, size (W/H/D), height and rotation, save it to the site catalog, or apply a texture. The Name shows on the support\'s list row and is reused as the default when saving to the catalog. The Texture list offers the site catalog\'s textures plus "None (white)". Newly-added site-catalog supports appear in the sidebar catalog after reloading the layout page.'},
                    {'name': 'Fit button (F key)', 'input_type': 'button / keyboard', 'purpose': 'Resets zoom and pan so the whole current wall fits the available canvas.'},
                    {'name': 'Measure button (M key)', 'input_type': 'button / keyboard', 'purpose': 'Select exactly two items and click Measure (or press M) to show, in inches: the centre-to-centre offsets (Δx, Δy, and Δz if applicable) and straight-line distance, plus the closest edge-to-edge gap horizontally and vertically (0 means they overlap on that axis).'},
                    {'name': 'Ruler button (+ 0: left/centre)', 'input_type': 'button (toggle)', 'purpose': 'Shows a ruler along all four wall edges — long ticks every 10 inches, short ticks every inch, big ticks labelled with their distance in inches from zero. Horizontal is measured from the LEFT edge (matching the Horiz field) and vertical from the floor. The "0: left / centre" button switches the horizontal zero to the wall centre (useful for symmetric obstacles). Tick lengths are a fixed size on the wall (they scale with zoom); inch ticks/labels appear once zoomed in enough to read them. Both toggles are remembered.'},
                    {'name': 'Snapshots button', 'input_type': 'button / panel', 'purpose': 'Save the current layout as a named restore point, or roll back to an earlier one. A snapshot is also taken automatically before every save and restore, so an accidental change or a stale tab overwriting your work can always be undone. Restores are themselves undoable (the current state is snapshotted first).'},
                    {'name': 'Distribute H / Distribute V buttons', 'input_type': 'button', 'purpose': 'Select multiple artworks (and optionally corner or obstacle markers) then click to space them with equal gaps. The outer two items act as anchors; inner items are redistributed. The gap on the outside of each anchor is half the gap between artworks.'},
                    {'name': 'Scroll wheel / pinch', 'input_type': 'gesture', 'purpose': 'Zoom in and out. Artwork images sharpen at higher zoom levels. Pan with W A S D keys or drag on empty canvas.'},
                ],
            },
            {
                'name': 'Curation Slideshow',
                'where_used': 'Reviews page → Artworks section → Curation Slideshow button',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Curation Slideshow',
                'fields': [
                    {'name': 'Selected / Undecided / Rejected', 'input_type': 'click buttons per artwork', 'purpose': 'Record your curation decision. Saves instantly. Keyboard shortcuts: S = Selected, R = Rejected, U = Undecided.'},
                    {'name': 'Jury scores panel', 'input_type': 'read-only display', 'purpose': 'Shows each juror\'s per-criterion scores and weighted total, plus the overall average across all jurors. Weak scores are highlighted in red. Artworks are sorted highest overall score first.'},
                    {'name': '↗ link / Enter / D key', 'input_type': 'navigation', 'purpose': 'Opens the artwork detail page. Respects blind review. Press Back to return to the slideshow at the same position.'},
                    {'name': 'Thumbnail strip', 'input_type': 'read-only display', 'purpose': 'Green border = Selected, red border = Rejected, gray = Undecided. Click any thumbnail to jump directly to that artwork.'},
                    {'name': 'Per-juror Slideshow (Reviews dashboard)', 'input_type': 'button in Juror Progress table', 'purpose': 'Launches a read-only slideshow filtered to one juror\'s scores, in that juror\'s scoring order. Useful for understanding an individual juror\'s perspective.'},
                ],
            },
            {
                'name': 'Submissions Page',
                'where_used': 'Show detail page → Submissions (curatorial button row)',
                'breadcrumb': 'Home > Shows > Select Show > Submissions',
                'fields': [
                    {'name': 'Decision dropdown per card', 'input_type': 'dropdown select', 'purpose': 'Set an individual submission to Undecided, Selected, or Rejected. After changing a card, the page automatically scrolls to the next card in the section so you do not lose your place.'},
                    {'name': 'Weighted score on card', 'input_type': 'read-only display', 'purpose': 'Each card shows the weighted jury score (e.g. 72.50/100 weighted) or the plain average if no rubric is defined. Cards within each section are sorted highest score first.'},
                    {'name': 'Selected section heading', 'input_type': 'read-only display', 'purpose': 'Shows the total width (in inches) of all selected flat wall artworks (depth = 0 or unset). Use this to estimate wall space needed for the selection.'},
                    {'name': 'Curation Slideshow button (per section)', 'input_type': 'button', 'purpose': 'Launches the Curation Slideshow filtered to just that section (Undecided, Selected, or Rejected).'},
                    {'name': '☑ All button (per section)', 'input_type': 'button', 'purpose': 'Selects all cards in that section. Hold Shift while clicking to add to the current selection instead of replacing it.'},
                    {'name': 'Card click (bulk select)', 'input_type': 'click on card background', 'purpose': 'Click the background of any card (not its links or dropdown) to toggle it into the bulk selection. Selected cards show a blue outline.'},
                    {'name': 'Shift+click (range select)', 'input_type': 'shift+click', 'purpose': 'Selects all cards between the last clicked card and the current one within the same section.'},
                    {'name': 'Click-and-drag (rubber-band select)', 'input_type': 'drag on grid background', 'purpose': 'Click and drag on the empty grid background to draw a selection rectangle. All cards whose centre falls inside the rectangle are selected when you release. Hold Shift while dragging to add to the existing selection.'},
                    {'name': 'Bulk action bar', 'input_type': 'fixed bar (bottom of screen)', 'purpose': 'Appears automatically when one or more cards are selected. Shows the count and three buttons — → Undecided, → Selected, → Rejected — that move all selected submissions at once with a single request. ✕ Clear deselects everything.'},
                ],
            },
            {
                'name': 'Submission Status Form (legacy grid)',
                'where_used': 'Open call submissions review page',
                'breadcrumb': 'Home > Shows > Select Show > Submissions',
                'fields': [
                    {'name': 'status per card', 'input_type': 'dropdown select per card', 'purpose': 'Set each submission to Undecided, Selected, or Rejected. Cards are sorted by weighted score within each section.'},
                ],
            },
            {
                'name': 'Promote Artworks',
                'where_used': 'Open call promotion page',
                'breadcrumb': 'Home > Shows > Select Show > Promote',
                'fields': [
                    {'name': '(confirm button)', 'input_type': 'form submit', 'purpose': 'Adds all Selected artworks and their artists to the show, sets the status to Published, and sends acceptance/rejection emails to every submitting artist — all in one step.'},
                ],
            },
            {
                'name': 'Event Form',
                'where_used': 'Event create/edit pages',
                'breadcrumb': 'Home > Events > New or Event Detail > Edit',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Event title.'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Public event description.'},
                    {'name': 'show', 'input_type': 'dropdown select', 'purpose': 'Show this event belongs to.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Event image shown on detail pages.'},
                    {'name': 'date', 'input_type': 'date input', 'purpose': 'Calendar date for the event.'},
                    {'name': 'start', 'input_type': 'time input', 'purpose': 'Event start time.'},
                    {'name': 'end', 'input_type': 'time input', 'purpose': 'Event end time.'},
                    {'name': 'tags', 'input_type': 'multi-select', 'purpose': 'Event tags used for filtering and curation.'},
                ],
            },
            {
                'name': 'Juror Assignment',
                'where_used': 'Show reviews page → Manage jurors',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Manage jurors',
                'fields': [
                    {'name': 'artist', 'input_type': 'dropdown select', 'purpose': 'Choose an artist with a linked user account to assign as juror for this show. Once assigned they can log in and score submitted artworks.'},
                ],
            },
            {
                'name': 'Rubric Criteria Form',
                'where_used': 'Show reviews → Manage rubric criteria',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Manage rubric criteria',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Criterion label shown to jurors when scoring, e.g. "Originality" or "Technical execution".'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Optional guidance to jurors explaining what to consider for this criterion.'},
                    {'name': 'weight', 'input_type': 'numeric input', 'purpose': 'Relative importance of this criterion. Higher weight contributes more to the composite score. For example, weights of 2, 1, 1 give the first criterion twice the influence.'},
                    {'name': 'order', 'input_type': 'numeric input', 'purpose': 'Display order shown to jurors. Lower numbers appear first. Use 0, 10, 20 etc. to leave room for reordering.'},
                    {'name': 'DELETE', 'input_type': 'checkbox', 'purpose': 'Check to remove this criterion. Deleting a criterion also removes all juror scores for it.'},
                ],
            },
            {
                'name': 'Curator Review Edit Form',
                'where_used': 'Artwork reviews detail (curator view)',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Select Artwork > Edit Review',
                'fields': [
                    {'name': 'rating', 'input_type': 'number input (0–100)', 'purpose': 'Adjust juror score when corrections are required.'},
                    {'name': 'body', 'input_type': 'multi-line text area', 'purpose': 'Adjust juror note text when needed.'},
                ],
            },
        ],
    },
    'juror': {
        'title': 'Juror Guide',
        'summary': 'Jurors review and score artworks for the specific shows they have been assigned to.',
        'allowed_actions': [
            'Access the Reviews page for shows you have been assigned to as juror.',
            'Use the Review Slideshow for fast, efficient scoring: image on the left, scoring buttons on the right, instant save with no Submit button.',
            'Score each submitted artwork using five levels: Weak, Developing, Solid, Strong, Exceptional (mapped to 10, 30, 50, 70, 90). If no rubric is defined, give an overall 0–100 rating.',
            'Auto-advance moves to the next unscored artwork automatically once all criteria are scored.',
            'Press Enter or D in the slideshow to open the artwork detail page (blind if the show uses blind review). Press Back to return to the slideshow.',
            'Alternatively, score artworks individually from the Pending Review list on the Reviews page.',
            'You can return to update your scores at any time before the curator closes the review phase.',
            'Optionally add qualitative review notes alongside your scores.',
        ],
        'forms': [
            {
                'name': 'Review Slideshow',
                'where_used': 'Reviews page → Review Slideshow button',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Review Slideshow',
                'fields': [
                    {'name': 'Weak / Developing / Solid / Strong / Exceptional', 'input_type': 'click buttons per criterion', 'purpose': 'Score each rubric criterion. Saves instantly on click. Keyboard shortcut: 1–5.'},
                    {'name': 'Auto', 'input_type': 'checkbox (top bar)', 'purpose': 'When checked, the slideshow advances automatically to the next unscored artwork after all criteria are scored.'},
                    {'name': 'Notes', 'input_type': 'text area (right panel)', 'purpose': 'Optional qualitative notes visible to the curator. Saved when you leave the field.'},
                    {'name': '↗ link / Enter / D key', 'input_type': 'navigation', 'purpose': 'Opens the artwork detail page. Respects blind review. Press Back to return to the slideshow.'},
                ],
            },
            {
                'name': 'Artwork Review Form (individual)',
                'where_used': 'Show review workflow — click Review on any artwork row',
                'breadcrumb': 'Home > Shows > Select Show > Reviews > Select Artwork',
                'fields': [
                    {'name': 'criterion scores', 'input_type': 'number input (0–100) per criterion', 'purpose': 'Score each rubric criterion if the curator has defined one.'},
                    {'name': 'rating', 'input_type': 'number input (0–100)', 'purpose': 'Overall score when no rubric is defined.'},
                    {'name': 'body', 'input_type': 'multi-line text area', 'purpose': 'Optional qualitative review notes visible to the curator.'},
                ],
            },
        ],
    },
    'staff': {
        'title': 'Staff Guide',
        'summary': 'Staff have full access across all shows, artists, artworks, and review workflows.',
        'allowed_actions': [
            'All curator capabilities across all shows and events.',
            'Create new shows (only staff can create; curators can edit assigned shows).',
            'Change show status to advance any show through its lifecycle from any show edit page.',
            'See all shows regardless of status.',
            'See all artists and artworks regardless of whether they are in any show.',
            'Assign artists as curators of shows via the Show Edit page — this grants them edit access and makes their artist profile publicly visible. Curators do not need linked user accounts to be assigned.',
            'Assign jurors to any show from the show\'s Reviews page.',
            'View and edit juror reviews across all shows.',
            'Link unlinked artist records to user accounts from /accounts/link-artists/.',
            'Log a sale for any artwork using the "Log sale" link in the button bar on the artwork detail page — records the collector, status, sale price, commission, and purchase date.',
            'Remove a collection claim on any artwork using the Remove link next to the claim on the artwork detail page.',
            'Create and edit sites, including room dimensions, per-wall texture images, and wall obstacles (doors, windows).',
            'Place artwork in the virtual room layout and view it in the 3D viewer.',
            'Edit and Delete links are shown only for records you can manage.',
        ],
        'forms': [
            {
                'name': 'Artwork Form (Staff Controls)',
                'where_used': 'Artwork create/edit pages',
                'breadcrumb': 'Me page > Artworks > New, or Artwork Detail > Edit',
                'fields': [
                    {'name': 'artists', 'input_type': 'multi-select', 'purpose': 'Associate one or more artists with the work.'},
                    {'name': 'shows', 'input_type': 'multi-select', 'purpose': 'Associate the artwork with one or more shows. Artwork becomes publicly visible once added to a show whose status is Published or Closed.'},
                    {'name': 'tags', 'input_type': 'multi-select', 'purpose': 'Internal or public categorization tags.'},
                ],
            },
            {
                'name': 'Log Sale Form',
                'where_used': 'Artwork detail page → Log sale (staff only)',
                'breadcrumb': 'Artwork Detail > Log sale',
                'fields': [
                    {'name': 'Collector', 'input_type': 'autocomplete search', 'purpose': 'Search for the buyer by name or email. Must be an existing user account.'},
                    {'name': 'Status', 'input_type': 'dropdown select', 'purpose': 'Confirmed (default) or Pending. Confirmed immediately records the sale; Pending notifies the collector for them to confirm.'},
                    {'name': 'Purchase date', 'input_type': 'date input', 'purpose': 'Date the sale took place.'},
                    {'name': 'Sale price', 'input_type': 'numeric input', 'purpose': 'Amount the collector paid for the work.'},
                    {'name': 'Commission', 'input_type': 'numeric input', 'purpose': 'Gallery commission amount retained from the sale price.'},
                    {'name': 'Notes', 'input_type': 'text input', 'purpose': 'Optional internal notes about the transaction.'},
                ],
            },
            {
                'name': 'Link Artist to User',
                'where_used': 'Staff-only artist linking page',
                'breadcrumb': '/accounts/link-artists/',
                'fields': [
                    {'name': 'artist', 'input_type': 'dropdown select', 'purpose': 'Unlinked artist record to claim. Only artists with no user account are listed.'},
                    {'name': 'user', 'input_type': 'dropdown select', 'purpose': 'User account to associate with the selected artist record.'},
                ],
            },
            {
                'name': 'Site Form',
                'where_used': 'Sites > New Site, or Site Detail > Edit',
                'breadcrumb': 'Sites > New Site',
                'fields': [
                    {'name': 'name', 'input_type': 'text input', 'purpose': 'Display name for the site, shown in listings, cards, and the navbar when browsing within that site.'},
                    {'name': 'slug', 'input_type': 'text input', 'purpose': 'URL-safe identifier used in all site-scoped URLs (e.g. /site/my-gallery/). Auto-generated from the name if left blank.'},
                    {'name': 'street', 'input_type': 'text input', 'purpose': 'Street address shown on the site detail page.'},
                    {'name': 'city', 'input_type': 'text input', 'purpose': 'City shown on the site card and detail page.'},
                    {'name': 'state', 'input_type': 'text input', 'purpose': 'State, province, or region.'},
                    {'name': 'postal_code', 'input_type': 'text input', 'purpose': 'ZIP or postal code.'},
                    {'name': 'country', 'input_type': 'text input', 'purpose': 'Country (defaults to USA).'},
                    {'name': 'latitude / longitude', 'input_type': 'decimal inputs', 'purpose': 'Geographic coordinates used to place the site as a pin on the Sites map. Fill in manually or click "Look up coordinates from address" to geocode from the address fields.'},
                    {'name': 'email', 'input_type': 'email input', 'purpose': 'Public contact email for the site.'},
                    {'name': 'phone', 'input_type': 'text input', 'purpose': 'Public contact phone number.'},
                    {'name': 'instagram', 'input_type': 'text input', 'purpose': 'Instagram handle for the site.'},
                    {'name': 'website', 'input_type': 'url input', 'purpose': 'External website URL for the gallery location.'},
                    {'name': 'description', 'input_type': 'multi-line text area', 'purpose': 'Public description shown on the site detail page.'},
                    {'name': 'image', 'input_type': 'file upload', 'purpose': 'Hero image shown on the site card and detail page.'},
                    {'name': 'icon', 'input_type': 'file upload', 'purpose': 'Small logo or icon (ideally square, at least 32 × 32 px) shown in the navbar and site list cards when browsing within that site.'},
                    {'name': 'status', 'input_type': 'dropdown select', 'purpose': 'Draft — site is hidden from public visitors. Published — site is visible to everyone and appears on the map.'},
                ],
            },
            {
                'name': 'Room Configuration Form',
                'where_used': 'Site edit page → Room Configuration section',
                'breadcrumb': 'Sites > Site Detail > Edit > Room Configuration',
                'fields': [
                    {'name': 'width_in', 'input_type': 'numeric input', 'purpose': 'Room width in inches (east-west dimension).'},
                    {'name': 'depth_in', 'input_type': 'numeric input', 'purpose': 'Room depth in inches (north-south dimension).'},
                    {'name': 'height_in', 'input_type': 'numeric input', 'purpose': 'Ceiling height in inches.'},
                    {'name': 'wall_n_image / wall_e_image / wall_s_image / wall_w_image', 'input_type': 'file upload (×4)', 'purpose': 'Texture image for the North, East, South, and West walls. Leave blank for a plain white surface. Used in the 3D viewer.'},
                    {'name': 'floor_image', 'input_type': 'file upload', 'purpose': 'Texture image for the floor. Leave blank for a plain white surface.'},
                    {'name': 'ceiling_image', 'input_type': 'file upload', 'purpose': 'Texture image for the ceiling. Leave blank for a plain white surface.'},
                ],
            },
            {
                'name': 'Wall Obstacle Form',
                'where_used': 'Site edit page → Walls & Obstacles section (one formset per obstacle)',
                'breadcrumb': 'Sites > Site Detail > Edit > Walls & Obstacles',
                'fields': [
                    {'name': 'label', 'input_type': 'text input', 'purpose': 'Name shown in the layout editor, e.g. "Front door" or "Window". Leaving this blank skips the row.'},
                    {'name': 'wall', 'input_type': 'dropdown select', 'purpose': 'Which wall the obstacle is on: N, E, S, or W.'},
                    {'name': 'x_in', 'input_type': 'numeric input', 'purpose': 'Horizontal position of the obstacle\'s left edge, measured in inches from the left edge of the wall.'},
                    {'name': 'y_in', 'input_type': 'numeric input', 'purpose': 'Vertical position of the obstacle\'s bottom edge, measured in inches from the floor.'},
                    {'name': 'w_in', 'input_type': 'numeric input', 'purpose': 'Width of the obstacle in inches.'},
                    {'name': 'h_in', 'input_type': 'numeric input', 'purpose': 'Height of the obstacle in inches.'},
                ],
            },
            {
                'name': 'Show Form (Staff Fields)',
                'where_used': 'Show create/edit pages',
                'breadcrumb': 'Shows > New (top of page) or Show Detail > Edit',
                'fields': [
                    {'name': 'status', 'input_type': 'dropdown select', 'purpose': 'Controls the show lifecycle and public visibility. Only curators and staff can change this field.'},
                    {'name': 'curators', 'input_type': 'multi-select', 'purpose': 'Assign artists as curators. All artists are listed, including those without user accounts — historical curator credits are preserved.'},
                    {'name': 'show_type', 'input_type': 'dropdown select', 'purpose': 'Gallery Show or Public Art Site. Affects the badge and display on show cards.'},
                    {'name': 'location', 'input_type': 'text area', 'purpose': 'Address or supplementary installation notes for public art shows.'},
                    {'name': 'sites', 'input_type': 'multi-select', 'purpose': 'Sites this show is associated with.'},
                ],
            },
        ],
    },
}
