from django.urls import path, re_path

from gallery.views.placards import placard_html, placard_json
from gallery.views.thumbnails import regenerate_artwork_thumbnail, regenerate_artist_thumbnail
from gallery.views import (
    ArtistCreateView,
    ArtistDeleteView,
    ArtistDetailView,
    ArtistListView,
    ArtistMailChimpView,
    ArtistUpdateView,
    EventCreateView,
    EventDeleteView,
    EventDetailView,
    EventListView,
    EventUpdateView,
    ArtworkCreateView,
    ArtworkDeleteView,
    ArtworkDetailView,
    ArtworkListView,
    ArtworkUpdateView,
    artwork_inquire,
    artwork_submit,
    invite_artists,
    show_submissions,
    promote_artworks,
    transition_show_status,
    update_submission_status,
    renumber_artworks,
    retract_submission,
    send_submission_reminders,
    SearchResultsListView,
    ShowCreateView,
    ShowDeleteView,
    ShowDetailView,
    ShowCatalogView,
    ShowInstagramView,
    ShowListView,
    ShowPlacardsView,
    ShowUpdateView,
    redirect_to_latest_show,
)

app_name = 'gallery'

urlpatterns = [
    path('artwork/<int:pk>/regenerate-thumbnail/', regenerate_artwork_thumbnail, name='regenerate_artwork_thumbnail'),
    path('artist/<int:pk>/regenerate-thumbnail/', regenerate_artist_thumbnail, name='regenerate_artist_thumbnail'),
    path('placard/<int:number>/', placard_html, name='placard_html'),
    path('placard/<int:number>/data/', placard_json, name='placard_json'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/submit/$', artwork_submit, name='artwork_submit'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/invite/$', invite_artists, name='invite_artists'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/submissions/$', show_submissions, name='show_submissions'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/submissions/remind/$', send_submission_reminders, name='send_submission_reminders'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/promote/$', promote_artworks, name='promote_artworks'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/renumber/$', renumber_artworks, name='renumber_artworks'),
    path('submission/<int:pk>/retract/', retract_submission, name='retract_submission'),
    path('submission/<int:pk>/status/', update_submission_status, name='update_submission_status'),
    path('artists/', ArtistListView.as_view(), name='artist_list'),
    path('artists/mailchimp', ArtistMailChimpView.as_view(), name='artist_mailchimp_list'),
    path('artist/<int:pk>/', ArtistDetailView.as_view(), name='artist_detail'),
    path('artist/<int:pk>/edit/', ArtistUpdateView.as_view(), name='artist_edit'),
    path('artist/<int:pk>/delete/', ArtistDeleteView.as_view(), name='artist_delete'),
    path('artist/new/', ArtistCreateView.as_view(), name='artist_new'),
    path('artist/search/', SearchResultsListView.as_view(), name='search_results'),
    re_path(r'^artist/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ArtistDetailView.as_view(), name='artist_detail'),
    path('artworks/', ArtworkListView.as_view(), name='artwork_list'),
    path('artwork/<int:pk>/', ArtworkDetailView.as_view(), name='artwork_detail'),
    path('artwork/<int:pk>/edit/', ArtworkUpdateView.as_view(), name='artwork_edit'),
    path('artwork/<int:pk>/delete/', ArtworkDeleteView.as_view(), name='artwork_delete'),
    path('artwork/<int:pk>/inquire/', artwork_inquire, name='artwork_inquire'),
    path('artwork/new/', ArtworkCreateView.as_view(), name='artwork_new'),
    re_path(r'^artwork/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ArtworkDetailView.as_view(), name='artwork_detail'),
    path('shows/', ShowListView.as_view(), name='show_list'),
    path('show/latest', redirect_to_latest_show, name='show_latest'),
    path('show/<int:pk>/', ShowDetailView.as_view(), name='show_detail'),
    path('show/catalog/<int:pk>/', ShowCatalogView.as_view(), name='show_catalog'),
    re_path(r'^show/catalog/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ShowCatalogView.as_view(), name='show_catalog'),
    path('show/placards/<int:pk>/', ShowPlacardsView.as_view(), name='show_placards_detail'),
    re_path(r'^show/placards/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ShowPlacardsView.as_view(), name='show_placards_detail'),
    path('show/instagram/<int:pk>/', ShowInstagramView.as_view(), name='show_instagram_detail'),
    re_path(r'^show/instagram/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ShowInstagramView.as_view(), name='show_instagram_detail'),
    path('show/<int:pk>/transition/', transition_show_status, name='transition_show_status'),
    path('show/<int:pk>/edit/', ShowUpdateView.as_view(), name='show_edit'),
    path('show/<int:pk>/delete/', ShowDeleteView.as_view(), name='show_delete'),
    path('show/new/', ShowCreateView.as_view(), name='show_new'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ShowDetailView.as_view(), name='show_detail'),
    path('events/', EventListView.as_view(), name='event_list'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('event/<int:pk>/edit/', EventUpdateView.as_view(), name='event_edit'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('event/new/', EventCreateView.as_view(), name='event_new'),
    re_path(r'^event/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', EventDetailView.as_view(), name='event_detail'),
]
