from django.urls import path, re_path

from gallery.views import (
    ArtistCreateView,
    ArtistDeleteView,
    ArtistDetailView,
    ArtistListView,
    ArtistMailChimpView,
    ArtistUpdateView,
    EventCreateView,
    EventDeleteView,
    EventDetailView,
    EventListView,
    EventUpdateView,
    ArtworkCreateView,
    ArtworkDeleteView,
    ArtworkDetailView,
    ArtworkListView,
    ArtworkUpdateView,
    ArtistOpenCallView,
    OpenCallDashboardView,
    SearchResultsListView,
    ShowCreateView,
    ShowDeleteView,
    ShowDetailView,
    ShowInstagramView,
    ShowListView,
    ShowPlacardsView,
    ShowUpdateView,
    redirect_to_latest_show,
)

app_name = 'gallery'

urlpatterns = [
    path('open-call/', OpenCallDashboardView.as_view(), name='open_call_dashboard'),
    path('open-call/my/', ArtistOpenCallView.as_view(), name='artist_open_call'),
    path('artists/', ArtistListView.as_view(), name='artist_list'),
    path('artists/mailchimp', ArtistMailChimpView.as_view(), name='artist_mailchimp_list'),
    path('artist/<int:pk>/', ArtistDetailView.as_view(), name='artist_detail'),
    path('artist/<int:pk>/edit/', ArtistUpdateView.as_view(), name='artist_edit'),
    path('artist/<int:pk>/delete/', ArtistDeleteView.as_view(), name='artist_delete'),
    path('artist/new/', ArtistCreateView.as_view(), name='artist_new'),
    path('artist/search/', SearchResultsListView.as_view(), name='search_results'),
    re_path(r'^artist/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ArtistDetailView.as_view(), name='artist_detail'),
    path('artworks/', ArtworkListView.as_view(), name='artwork_list'),
    path('artwork/<int:pk>/', ArtworkDetailView.as_view(), name='artwork_detail'),
    path('artwork/<int:pk>/edit/', ArtworkUpdateView.as_view(), name='artwork_edit'),
    path('artwork/<int:pk>/delete/', ArtworkDeleteView.as_view(), name='artwork_delete'),
    path('artwork/new/', ArtworkCreateView.as_view(), name='artwork_new'),
    re_path(r'^artwork/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ArtworkDetailView.as_view(), name='artwork_detail'),
    path('shows/', ShowListView.as_view(), name='show_list'),
    path('show/latest', redirect_to_latest_show, name='show_latest'),
    path('show/<int:pk>/', ShowDetailView.as_view(), name='show_detail'),
    path('show/placards/<int:pk>/', ShowPlacardsView.as_view(), name='show_placards_detail'),
    re_path(r'^show/placards/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ShowPlacardsView.as_view(), name='show_placards_detail'),
    path('show/instagram/<int:pk>/', ShowInstagramView.as_view(), name='show_instagram_detail'),
    re_path(r'^show/instagram/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ShowInstagramView.as_view(), name='show_instagram_detail'),
    path('show/<int:pk>/edit/', ShowUpdateView.as_view(), name='show_edit'),
    path('show/<int:pk>/delete/', ShowDeleteView.as_view(), name='show_delete'),
    path('show/new/', ShowCreateView.as_view(), name='show_new'),
    re_path(r'^show/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', ShowDetailView.as_view(), name='show_detail'),
    path('events/', EventListView.as_view(), name='event_list'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('event/<int:pk>/edit/', EventUpdateView.as_view(), name='event_edit'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('event/new/', EventCreateView.as_view(), name='event_new'),
    re_path(r'^event/(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)/$', EventDetailView.as_view(), name='event_detail'),
]
