# Generated by Django 5.1.2 on 2026-05-02 01:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0005_add_submission_deadline_to_show'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gallery.artwork')),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_reviews', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gallery.show')),
            ],
            options={
                'ordering': ['artwork__name', 'juror__last_name'],
                'unique_together': {('show', 'artwork', 'juror')},
            },
        ),
        migrations.CreateModel(
            name='ShowJuror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juror_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurors', to='gallery.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juror_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['show', 'user__last_name', 'user__first_name'],
                'unique_together': {('show', 'user')},
            },
        ),
    ]
