# Generated by Django 5.1.2 on 2026-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_weight_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriccriterion',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
