from gallery.views.artists import (
    ArtistCreateView,
    ArtistDeleteView,
    ArtistDetailView,
    ArtistListView,
    ArtistMailChimpView,
    ArtistUpdateView,
)
from gallery.views.artworks import (
    ArtworkCreateView,
    ArtworkDeleteView,
    ArtworkDetailView,
    ArtworkListView,
    ArtworkUpdateView,
    detail,
)
from gallery.views.events import (
    EventCreateView,
    EventDeleteView,
    EventDetailView,
    EventListView,
    EventUpdateView,
)
from gallery.views.exhibitions import (
    ShowCatalogView,
    ShowCreateView,
    ShowDeleteView,
    ShowDetailView,
    ShowInstagramView,
    ShowListView,
    ShowPlacardsView,
    ShowUpdateView,
    redirect_to_latest_show,
    transition_show_status,
)
from gallery.views.open_call import artwork_submit, invite_artists, show_submissions, promote_artworks, update_submission_status, renumber_artworks, retract_submission
from gallery.views.search import SearchResultsListView

__all__ = [
    'detail',
    'ArtistListView',
    'ArtistMailChimpView',
    'ArtistDetailView',
    'ArtistUpdateView',
    'ArtistDeleteView',
    'ArtistCreateView',
    'ArtworkListView',
    'ArtworkDetailView',
    'ArtworkUpdateView',
    'ArtworkDeleteView',
    'ArtworkCreateView',
    'ShowCatalogView',
    'ShowListView',
    'ShowDetailView',
    'ShowPlacardsView',
    'ShowInstagramView',
    'ShowUpdateView',
    'ShowDeleteView',
    'ShowCreateView',
    'redirect_to_latest_show',
    'transition_show_status',
    'artwork_submit',
    'invite_artists',
    'show_submissions',
    'promote_artworks',
    'update_submission_status',
    'retract_submission',
    'EventListView',
    'EventDetailView',
    'EventUpdateView',
    'EventDeleteView',
    'EventCreateView',
    'SearchResultsListView',
]
