# Generated by Django 4.2.4 on 2025-07-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0012_piece_replacement_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='curators',
            field=models.ManyToManyField(to='piece.artist'),
        ),
    ]
