# Generated by Django 4.2.4 on 2025-08-10 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0014_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='show',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
