# Generated by Django 4.2.4 on 2025-08-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0015_show_end_show_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='show',
            name='closing_end',
        ),
        migrations.RemoveField(
            model_name='show',
            name='closing_start',
        ),
        migrations.RemoveField(
            model_name='show',
            name='opening',
        ),
        migrations.RemoveField(
            model_name='show',
            name='opening_end',
        ),
        migrations.RemoveField(
            model_name='show',
            name='opening_start',
        ),
    ]
