# Generated by Django 4.2.4 on 2025-08-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0016_remove_show_closing_remove_show_closing_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='curator',
        ),
    ]
