# Generated by Django 5.1.2 on 2025-09-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0018_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to='artist_images'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='artists',
            field=models.ManyToManyField(related_name='pieces', to='piece.artist'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(null=True, upload_to='piece_images'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='shows',
            field=models.ManyToManyField(related_name='pieces', to='piece.show'),
        ),
    ]
