# Generated by Django 5.1.2 on 2025-09-16 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0019_alter_artist_image_alter_piece_artists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
