# Generated by Django 5.1.2 on 2025-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0020_alter_artist_options_alter_piece_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LxWxD in inches'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Numeric price'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='pricing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anything more sophisticated like "Upon request" or "NFS"'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='replacement_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Redo cost in the rare case that it gets stolen or damaged'),
        ),
    ]
