# Generated by Django 5.1.2 on 2025-09-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0021_alter_piece_dimensions_alter_piece_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dimensions: LxWxD in inches'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price: Numeric price'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='pricing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pricing: anything more sophisticated like "Upon request" or "NFS"'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='replacement_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Replacment Cost: redo cost in the rare case that it gets stolen or damaged'),
        ),
    ]
