# Generated by Django 5.1.2 on 2025-09-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0022_alter_piece_dimensions_alter_piece_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram: your handle starting with @'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price: numeric price'),
        ),
    ]
