# Generated by Django 5.1.2 on 2025-09-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0023_alter_artist_instagram_alter_piece_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='installation',
            field=models.TextField(blank=True, null=True, verbose_name='Installation: optional instructions for installing your work'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start_year: only fill in if different than end_year'),
        ),
    ]
