# Generated by Django 5.1.2 on 2025-10-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0024_alter_piece_installation_alter_piece_start_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-start']},
        ),
    ]
